export type HoverInspectionSample = {
  imageX: number;
  imageY: number;
  worldX: number | null;
  worldY: number | null;
  rawZ: number | null;
  normalizedHeight: number | null;
  planeHeight: number | null;
  residualMm: number | null;
  displayClippedHeight: number | null;
  clipped: boolean | null;
  valid: boolean | null;
  intensity: number | null;
  hoveredObjectId: number | null;
  selectedObjectId: number | null;
  units: string | null;
  sourceArtifactId: string | null;
  displaySemantic: string | null;
  semanticField: string | null;
  valueKind: "raw_z" | "normalized_height" | "unknown";
  coordDebug?: {
    clientX: number;
    clientY: number;
    frameLeft: number;
    frameTop: number;
    frameWidth: number;
    frameHeight: number;
    imageLeft: number;
    imageTop: number;
    imageWidth: number;
    imageHeight: number;
    renderedX: number;
    renderedY: number;
    naturalX: number;
    naturalY: number;
    sourceArrayX: number;
    sourceArrayY: number;
    roiOriginX: number;
    roiOriginY: number;
    roiWidth: number;
    roiHeight: number;
    finalSampleX: number;
    finalSampleY: number;
    renderMode: "full_image" | "roi_crop";
    renderedRgb: [number, number, number] | null;
    sampledHeight: number | null;
    interpolatedFromNearest?: boolean;
    denseSourceX?: number;
    denseSourceY?: number;
    roiPurpose?: string;
    renderCoordinateSpace?: string;
    sourceShape?: [number, number] | null;
    renderedPngShape?: [number, number] | null;
    numericArrayShape?: [number, number] | null;
    validMaskShape?: [number, number] | null;
  };
};
