export type StudioHelpOptionDetail = {
  value: string;
  label: string;
  description: string;
};

export type StudioHelpEntry = {
  title: string;
  summary: string;
  details: string;
  consumes?: string;
  produces?: string;
  supportType?: string;
  fragmentedGuidance?: string;
  mergedGuidance?: string;
  overTuningRisk?: string;
  whenToIncrease?: string;
  whenToDecrease?: string;
  affects?: string[];
  symptoms?: string[];
  related?: string[];
  optionDetails?: StudioHelpOptionDetail[];
};

function help(entry: StudioHelpEntry): StudioHelpEntry {
  return entry;
}

export const STUDIO_HELP_CONTENT: Record<string, StudioHelpEntry> = {
  "detect_reference_surface.process.gradient_low_gradient": help({
    title: "Gradient / low-gradient",
    summary: "Filters the heightmap down to calmer, flatter candidate pixels that could belong to the reference support.",
    details: "This step is the first real support gate. It decides which valid ROI pixels even get a chance to become reference support.",
    consumes: "Valid ROI and depth-gradient magnitude.",
    produces: "Low-gradient candidate mask plus early rejection diagnostics.",
    supportType: "Affects logical support by deciding which pixels are eligible for later connectivity and clustering.",
    fragmentedGuidance: "If the belt breaks up too early, make the low-gradient gate more permissive so more belt pixels survive into component formation.",
    mergedGuidance: "If object texture leaks into support, make the low-gradient gate stricter so high-variation object regions drop out sooner.",
    overTuningRisk: "An overly strict gate starves the rest of the pipeline; an overly loose gate pushes object texture downstream where it is harder to remove cleanly.",
    affects: ["Low-gradient mask", "Blob components", "Selected surface"],
    symptoms: ["Too much object texture leaks into support candidates", "Too little belt area survives into later steps"],
    related: ["Low-gradient mask", "Selected blob cluster", "Selected surface"],
  }),
  "detect_reference_surface.process.component_formation": help({
    title: "Component formation",
    summary: "Groups neighboring low-gradient pixels into connected candidate components or fragments.",
    details: "This stage turns surviving pixels into candidate regions that later splitting, clustering, and scoring can reason about.",
    consumes: "Low-gradient mask plus connectivity rules.",
    produces: "Blob/component masks and rejected-connection diagnostics.",
    supportType: "Affects logical support and connectivity-only structure before any fit-support trimming happens.",
    fragmentedGuidance: "If the belt falls into many tiny regions, relax connectivity so nearby belt pixels can stay in the same component.",
    mergedGuidance: "If object and belt stay fused, tighten connectivity so height jumps and steep local transitions break those links.",
    overTuningRisk: "Too much connectivity creates giant mixed components; too little connectivity creates shards that later scoring can mis-rank.",
    affects: ["Blob components", "Blob clusters", "Selected blob cluster"],
    symptoms: ["Object and belt merge into one component", "Belt breaks into many small fragments"],
    related: ["Blob components", "Height clustering", "Selected blob cluster"],
  }),
  "detect_reference_surface.process.height_border_detection": help({
    title: "Height-border detection",
    summary: "Builds the border-strength map that marks likely internal height cuts inside mixed components.",
    details: "This stage estimates where strong height transitions run through a candidate component before the splitter turns those signals into fragment boundaries.",
    consumes: "Eligible blob masks and local height variation inside those blobs.",
    produces: "Height-border strength, accepted cut diagnostics, and cut-ready boundary candidates.",
    supportType: "Affects logical support only indirectly by creating split cues; it is diagnostic until cuts are accepted.",
    fragmentedGuidance: "If belt texture is fragmenting the support, require stronger or longer borders so weak chevron texture stops looking like a real cut.",
    mergedGuidance: "If object and belt remain fused, make the detector more sensitive so the real boundary survives into splitting.",
    overTuningRisk: "Over-tuning can either carve the belt into texture-driven shards or erase real object boundaries completely.",
    affects: ["Height-border strength", "Cut mask", "Height-border fragments"],
    related: ["Height-border strength", "Height-border fragments", "Height-split blobs"],
  }),
  "detect_reference_surface.process.blob_splitting": help({
    title: "Blob splitting",
    summary: "Converts mixed candidate components into height-consistent fragments before clustering.",
    details: "This stage applies height-border cuts and optional histogram splitting so clustering works with fragments that better match physical support pieces.",
    consumes: "Eligible blobs, border-strength diagnostics, and optional histogram structure.",
    produces: "Height-border fragments, final split fragments, and split diagnostics.",
    supportType: "Affects logical support by redefining which connected regions later height clustering can score.",
    fragmentedGuidance: "If the belt is already fragmented, use stricter cuts and keep smaller rescue-friendly fragments alive only when they are clearly valid support.",
    mergedGuidance: "If object and belt remain merged, lower the barrier for useful cuts so the mixed component is actually split before clustering.",
    overTuningRisk: "Aggressive splitting creates tiny support islands and unstable scores; timid splitting leaves object and belt fused so every later stage inherits the mistake.",
    affects: ["Height-border fragments", "Height-split blobs", "Cluster inputs"],
    related: ["Height-border detection", "Fragment merge", "Height clustering"],
  }),
  "detect_reference_surface.process.fragment_merge": help({
    title: "Fragment merge",
    summary: "Reconnects fragments that were separated by weak or background-like boundaries.",
    details: "This rescue step is meant to undo safe over-splitting without letting obviously different object and belt regions fuse back together.",
    consumes: "Split fragments, local boundary strength, and median Z-gap checks across neighboring fragments.",
    produces: "Post-merge fragments and merge diagnostics.",
    supportType: "Affects logical support and connectivity only; it happens before final fit-support trimming.",
    fragmentedGuidance: "If valid belt strips were split apart, allow slightly larger Z gaps and slightly weaker boundaries so the belt reconnects.",
    mergedGuidance: "If object and belt are merging back together, tighten the rescue thresholds and keep merges limited to background-like boundaries.",
    overTuningRisk: "An overly generous rescue step can hide good splitting by fusing object fragments back into support.",
    affects: ["Post-merge fragments", "Cluster inputs", "Selected support connectivity"],
    related: ["Height-border fragments", "Height-split blobs", "Selected support"],
  }),
  "detect_reference_surface.process.height_clustering": help({
    title: "Height clustering",
    summary: "Groups components or fragments by height compatibility to form support candidates.",
    details: "This step consumes component summaries and height-spread diagnostics. It produces cluster candidates and their per-cluster stats. It matters because the selected blob cluster is chosen from these height-level groups, not from raw pixels directly.",
    consumes: "Component or fragment summaries and per-region height statistics.",
    produces: "Cluster candidates and per-cluster diagnostics.",
    supportType: "Affects logical support by deciding which fragments are considered one candidate support body.",
    fragmentedGuidance: "If one belt becomes several clusters, make earlier stages preserve more continuity before clustering.",
    mergedGuidance: "If object fragments stay mixed with support, splitting and merge-rescue settings usually need work before clustering can separate them.",
    overTuningRisk: "Trying to solve poor splitting purely at clustering time usually makes selection brittle and dataset-specific.",
    affects: ["Blob clusters", "Cluster score table", "Selected blob cluster"],
    symptoms: ["One physical support is split into multiple clusters", "Object fragments stay mixed with belt support"],
    related: ["Blob clusters", "Cluster score table", "Selected blob cluster"],
  }),
  "detect_reference_surface.process.cluster_scoring": help({
    title: "Cluster scoring",
    summary: "Ranks candidate clusters and chooses the best reference-support candidate.",
    details: "This step consumes cluster features such as size, border contact, constancy, coverage, and penalties. It produces the chosen cluster plus rejected-cluster diagnostics. It matters because this is where the pipeline decides which candidate should become the reference-support seed.",
    consumes: "Cluster-level size, shape, border-contact, and stability metrics.",
    produces: "Winning cluster plus rejected-cluster explanations.",
    supportType: "Affects logical support selection, not final fit support directly.",
    fragmentedGuidance: "If fragmentation creates many belt shards, fix splitting/merge behavior first so scoring sees a believable support candidate.",
    mergedGuidance: "If a mixed object+belt cluster keeps winning, make earlier separation stronger before trying to compensate here.",
    overTuningRisk: "Scoring tweaks can memorize one scan pattern while hiding upstream segmentation problems.",
    affects: ["Selected blob cluster", "Cluster score table", "Selected surface"],
    symptoms: ["Central object-like clusters beat border support", "Tiny border strips win unexpectedly"],
    related: ["Selected blob cluster", "Rejected blob clusters", "Selected surface"],
  }),
  "detect_reference_surface.process.selected_blob_cluster": help({
    title: "Selected blob cluster",
    summary: "The winning cluster before final support refinement.",
    details: "This is the last purely logical support choice before refinement, stripe suppression, and reference-model fitting change the mask further.",
    consumes: "The cluster-scoring decision and selected cluster mask.",
    produces: "Selected-cluster artifacts before refinement.",
    supportType: "Logical support only.",
    fragmentedGuidance: "If the selected cluster is too sparse or broken, revisit split and merge stages.",
    mergedGuidance: "If the selected cluster still contains object pixels, make earlier separation stronger before refinement tries to trim them away.",
    overTuningRisk: "Relying on downstream refinement to fix a bad cluster usually creates unstable fit support and suppression masks.",
    affects: ["Selected blob cluster", "Selected surface", "Plane inliers"],
    symptoms: ["The chosen support still contains uncertain, noisy, or border pixels"],
    related: ["Selected blob cluster", "Selected cluster to surface refinement", "Selected surface"],
  }),
  "detect_reference_surface.process.selected_surface": help({
    title: "Selected support",
    summary: "Final reference-support mask after refinement, validation, stripe cleanup, and fallback handling.",
    details: "This is the main logical support mask that downstream fitting starts from. It can differ a lot from the selected cluster because refinement and stripe suppression may add or remove pixels.",
    consumes: "Selected blob cluster plus refinement, stripe, and fallback rules.",
    produces: "Final selected support used as the source for model fitting.",
    supportType: "Logical support. It feeds fit support, suppression mask resolution, and diagnostics, but is not itself the final fit-support mask.",
    fragmentedGuidance: "If valid belt support disappears here, loosen refinement or preserve border-connected support before the model fit starts.",
    mergedGuidance: "If object pixels survive here, tighten refinement or upstream splitting so the fit does not start from a contaminated support.",
    overTuningRisk: "A support mask that is too small destabilizes fitting; one that is too loose contaminates the model and every downstream mask.",
    affects: ["Selected surface", "Plane inliers", "Residuals"],
    symptoms: ["Final support is smaller than the candidate cluster", "Fallback replaces the candidate support"],
    related: ["Selected blob cluster", "Plane inliers", "Residuals"],
  }),
  "detect_reference_surface.process.selected_support_lineage": help({
    title: "Selected support lineage",
    summary: "Step-by-step ledger from selected blob cluster to selected support, model support, and suppression mask.",
    details: "This view makes the lineage explicit: candidate refinement, stripe suppression, reference-model support, and suppression-mask resolution each get their own row with input/output/removed pixels.",
    consumes: "Selected-cluster lineage metadata and per-step support-loss artifacts.",
    produces: "Diagnostic ledger only.",
    supportType: "Diagnostic view covering logical support, fit support, and suppression mask transitions.",
    fragmentedGuidance: "Use the step-by-step losses to see exactly where fragmented belt support disappears.",
    mergedGuidance: "Use the removed/added steps to confirm whether merging is happening before or after model fitting.",
    overTuningRisk: "Tuning against only one lineage snapshot can overfit a special case instead of the real failure mode.",
    affects: ["Selected blob cluster", "Selected support", "Model support", "Suppression mask"],
    symptoms: ["Selected surface looks much smaller than the chosen cluster", "It is unclear whether refinement, stripes, or model residuals removed support"],
    related: ["Selected blob cluster", "Selected surface", "Plane inliers"],
  }),
  "detect_reference_surface.process.reference_model": help({
    title: "Reference model",
    summary: "Turns selected support into a fitted reference surface and resolves the downstream suppression mask.",
    details: "This stage decides which selected-support pixels survive model residual checks, which model is used, and which mask downstream segmentation should suppress.",
    consumes: "Selected support, model choice, and residual thresholds.",
    produces: "Reference-model fit support, plane inliers, residual diagnostics, and suppression mask.",
    supportType: "Affects fit support, suppression mask, and diagnostics. It does not create new logical support.",
    fragmentedGuidance: "If fragmented belt support is rejected by the fit, prefer a more tolerant model path before simply loosening residual thresholds.",
    mergedGuidance: "If object pixels contaminated selected support, stricter fit-support acceptance or a different model can prevent them from becoming suppression.",
    overTuningRisk: "Over-loose fit support can normalize against the object; over-strict fit support can erase real belt support and destabilize suppression.",
    affects: ["Plane inliers", "Reference model support", "Reference suppression mask"],
    related: ["Selected support", "Plane inliers", "Suppression mask"],
  }),
  "detect_reference_surface.artifact.selected_blob_cluster": help({
    title: "Selected blob cluster",
    summary: "This is the chosen height/blob cluster before final support refinement.",
    details: "It may still contain uncertain, noisy, or border pixels. The cluster was selected by scoring, but it is not yet the final reference-support mask used for plane fitting and normalization.",
    consumes: "Cluster scoring output.",
    produces: "Logical support candidate artifact.",
    supportType: "Logical support.",
    fragmentedGuidance: "If it is too broken, inspect split and merge behavior.",
    mergedGuidance: "If it still contains object material, inspect earlier separation stages.",
    overTuningRisk: "Treating this artifact as if it were final support hides important downstream trimming behavior.",
    affects: ["Selected cluster to surface refinement", "Selected surface"],
    related: ["Selected surface", "Cluster score table"],
  }),
  "detect_reference_surface.artifact.height_border_fragments": help({
    title: "Height-border fragments",
    summary: "Fragments produced immediately after height-border cuts are accepted.",
    details: "This artifact shows what the border splitter believes are separate support pieces before weak-boundary rescue or later clustering changes the grouping again.",
    consumes: "Height-border strength plus thresholded cut candidates.",
    produces: "Logical-support fragment masks and split diagnostics.",
    supportType: "Logical support only.",
    fragmentedGuidance: "If the belt explodes into many pieces here, raise min delta, percentile, smoothing, or min edge length.",
    mergedGuidance: "If object and belt are still one fragment here, lower the relevant cut thresholds so the real border is accepted.",
    overTuningRisk: "Overreacting to one noisy scan can make the border splitter too insensitive on clean object boundaries.",
    affects: ["Height-border fragments", "Fragment merge", "Height clustering"],
    related: ["Height-border strength", "Height-split blobs", "Fragment merge"],
  }),
  "detect_reference_surface.artifact.height_split_blobs": help({
    title: "Height-split blobs",
    summary: "Final fragment view after split and optional merge rescue have both run.",
    details: "This is the logical-support artifact that height clustering will actually consume.",
    consumes: "Height-border fragments plus optional weak-boundary rescue or histogram refinement.",
    produces: "Final logical fragments for clustering.",
    supportType: "Logical support only.",
    fragmentedGuidance: "If valid belt support is still too broken here, merge rescue is too strict or earlier splitting is too aggressive.",
    mergedGuidance: "If object and belt remain fused here, merge rescue may be too permissive or the split detector is too weak.",
    overTuningRisk: "Chasing a perfect fragment count can make clustering less robust across different belt textures.",
    affects: ["Height clustering", "Selected support"],
    related: ["Height-border fragments", "Fragment merge", "Height clusters"],
  }),
  "detect_reference_surface.artifact.selected_surface": help({
    title: "Selected support",
    summary: "This is the final selected reference support mask after refinement, size validation, border preservation, and fallback.",
    details: "It can be smaller or different from the selected blob cluster. This final support is what downstream plane fitting, normalization, and segmentation use as the support source.",
    consumes: "Selected cluster plus refinement and stripe suppression.",
    produces: "Final logical support mask.",
    supportType: "Logical support.",
    fragmentedGuidance: "If belt support becomes too sparse here, loosen the trimming stages before touching the model fit.",
    mergedGuidance: "If the object is still inside support here, tighten upstream split/refinement behavior before relying on model rejection.",
    overTuningRisk: "Using this mask to compensate for a bad cluster can create unstable downstream fit support.",
    affects: ["Plane inliers", "Residuals", "Normalization and segmentation"],
    related: ["Selected blob cluster", "Plane inliers", "Residuals"],
  }),
  "detect_reference_surface.artifact.reference_model_support": help({
    title: "Reference model support",
    summary: "Pixels from selected support that the chosen reference model accepts as fit support.",
    details: "This is the mask that actually anchors the fitted model. It is usually stricter than selected support because residual checks can reject support pixels that do not agree with the model.",
    consumes: "Selected support, chosen model, and residual thresholds.",
    produces: "Fit-support mask plus residual rejection diagnostics.",
    supportType: "Fit support.",
    fragmentedGuidance: "If fragmented but valid belt pieces are rejected here, try a more appropriate model or slightly looser residual acceptance only after confirming the selected support is good.",
    mergedGuidance: "If object pixels are sneaking into fit support, tighten residual acceptance or change the model so object-like deviations do not pass.",
    overTuningRisk: "Over-loose fit support can fit through object pixels; over-tight fit support can leave too little area for a stable model.",
    affects: ["Plane inliers", "Residual QA", "Suppression mask policy"],
    related: ["Selected support", "Suppression mask", "Residuals"],
  }),
  "detect_reference_surface.artifact.reference_suppression_mask": help({
    title: "Reference suppression mask",
    summary: "Support-derived mask that downstream segmentation removes from the foreground search.",
    details: "This is the handoff artifact for segmentation. Depending on policy, it can come from selected support, expanded support, or final model inliers.",
    consumes: "Selected support, fit support, and suppression-mask policy.",
    produces: "Suppression mask only.",
    supportType: "Suppression mask.",
    fragmentedGuidance: "If the suppression mask leaves belt gaps that later become false objects, preserve more valid support earlier or use a less strict suppression source.",
    mergedGuidance: "If the suppression mask eats into the object, make sure object pixels are removed from selected/fit support before they become suppression.",
    overTuningRisk: "Over-suppressing deletes real objects; under-suppressing leaves belt remnants for segmentation to mistake as foreground.",
    affects: ["Segmentation handoff", "Foreground cleanup"],
    related: ["Selected support", "Reference model support", "Plane inliers"],
  }),
  "detect_reference_surface.artifact.plane_inliers": help({
    title: "Plane inliers",
    summary: "Pixels that agree with the fitted reference model closely enough to be treated as model support.",
    details: "This artifact consumes the final selected surface and the chosen reference model. It produces the mask used to judge fit quality and downstream suppression behavior.",
    consumes: "Selected support and fitted model.",
    produces: "Fit-support/inlier mask.",
    supportType: "Fit support.",
    fragmentedGuidance: "If inliers are much smaller than selected support, review model choice before loosening thresholds.",
    mergedGuidance: "If object pixels remain inliers, support contamination or an overly tolerant threshold is likely.",
    overTuningRisk: "Threshold changes can mask a wrong model choice and make the fit unstable elsewhere.",
    affects: ["Residual QA", "Reference suppression", "Normalization"],
    symptoms: ["True support pixels are rejected by the fit", "Inlier ratio is unexpectedly low"],
    related: ["Selected surface", "Residuals"],
  }),
  "detect_reference_surface.artifact.residuals": help({
    title: "Residuals",
    summary: "Per-pixel distance from the chosen reference model.",
    details: "Residuals consume the fitted plane or constant-Z model and show where the model disagrees with the measured surface. They matter for fit QA and for understanding whether model choice or support selection is causing poor normalization.",
    consumes: "Fitted reference model and measured surface.",
    produces: "Diagnostic error map and histogram.",
    supportType: "Diagnostics only.",
    fragmentedGuidance: "If fragmented support causes patchy residuals, inspect selected support and model support together.",
    mergedGuidance: "If merged object pixels create localized high residuals, upstream separation is probably still too weak.",
    overTuningRisk: "Residual thresholds tuned from a single texture pattern often fail on other belt scans.",
    affects: ["Plane QA", "Reference-model selection"],
    symptoms: ["Large belt regions show high residual error", "Model fallback may be triggered"],
    related: ["Selected surface", "Plane inliers"],
  }),
  "detect_reference_surface.role.logical_support": help({
    title: "Logical support",
    summary: "Mask used to represent which pixels conceptually belong to the reference support before model-fit acceptance.",
    details: "Logical support is the pipeline's semantic belief about belt/reference membership. It can still be refined or rejected later by stripe logic and model residual checks.",
    consumes: "Upstream candidate, split, cluster, and refinement decisions.",
    produces: "Support-source masks for downstream fitting.",
    supportType: "Logical support.",
    fragmentedGuidance: "If logical support is too fragmented, fix connectivity, splitting, or rescue before touching fit-support thresholds.",
    mergedGuidance: "If object and belt are merged, upstream separation must improve before fit support can be trusted.",
    overTuningRisk: "Pushing logical support to solve every edge case often destabilizes the whole strategy path.",
  }),
  "detect_reference_surface.role.fit_support": help({
    title: "Fit support",
    summary: "Mask of support pixels that the reference model actually trusts for fitting or inlier validation.",
    details: "Fit support is downstream of logical support. It is usually smaller because the model can reject support pixels that disagree with the fitted surface.",
    consumes: "Selected support plus model residual checks.",
    produces: "Inlier or fit-support masks.",
    supportType: "Fit support.",
    fragmentedGuidance: "If valid support is lost here, check model choice and residual thresholds rather than only enlarging logical support.",
    mergedGuidance: "If object pixels survive here, selected support is contaminated or residual acceptance is too loose.",
    overTuningRisk: "Loose fit support can poison the model; strict fit support can leave too little area to fit reliably.",
  }),
  "detect_reference_surface.role.suppression_mask": help({
    title: "Suppression mask",
    summary: "Mask handed to downstream segmentation to remove belt/reference pixels from foreground detection.",
    details: "Suppression is not the same as selected support or fit support. It is the final removal policy applied when object segmentation runs.",
    consumes: "Selected support, fit support, and suppression policy.",
    produces: "Segmentation suppression mask.",
    supportType: "Suppression mask.",
    fragmentedGuidance: "If fragmented belt leaks through segmentation, the suppression source may be too strict or upstream support is too broken.",
    mergedGuidance: "If the object gets suppressed, object pixels are still present in whichever support mask the policy uses.",
    overTuningRisk: "Over-suppression deletes objects; under-suppression leaves belt texture as false positives.",
  }),
  "detect_reference_surface.role.connectivity_support": help({
    title: "Connectivity-only",
    summary: "Artifact used to explain how pixels were grouped, not to define final support by itself.",
    details: "These masks exist to show connectivity structure such as components or rejected edges. They are useful for diagnosis but are not authoritative fit-support masks.",
    consumes: "Low-gradient candidates and connectivity rules.",
    produces: "Connectivity diagnostics and grouping masks.",
    supportType: "Connectivity-only diagnostics that influence logical support upstream.",
    fragmentedGuidance: "If belt connectivity is too weak here, relax connectivity before later stages try to repair it.",
    mergedGuidance: "If connectivity already merges object and belt, later stages start at a disadvantage.",
    overTuningRisk: "Treating connectivity artifacts like final support can lead to the wrong stage being tuned.",
  }),
  "detect_reference_surface.role.diagnostic": help({
    title: "Diagnostic artifact",
    summary: "Artifact emitted to explain a decision rather than to serve as the authoritative support mask.",
    details: "Diagnostic artifacts help you see why support was added, split, merged, or rejected. They usually do not feed downstream stages directly.",
    consumes: "The stage's internal measurements or comparison masks.",
    produces: "Debug-only evidence such as strength maps, removed masks, or score tables.",
    supportType: "Diagnostics only.",
    fragmentedGuidance: "Use diagnostics to locate which stage is causing fragmentation before changing parameters.",
    mergedGuidance: "Use diagnostics to confirm whether object/belt merging happens before or after the current stage.",
    overTuningRisk: "Optimizing a diagnostic picture instead of the actual support masks can produce misleading improvements.",
  }),
  "detect_reference_surface.param.refine_by_mad": help({
    title: "Refine by MAD",
    summary: "Enables robust Z-band trimming around the selected cluster median.",
    details: "When enabled, the candidate cluster is narrowed using a median-absolute-deviation band before final support validation. This often removes noisy or off-height pixels before the selected surface is finalized.",
    consumes: "Selected cluster plus robust Z-spread statistics.",
    produces: "Trimmed selected-support candidate.",
    supportType: "Affects logical support before fit support.",
    affects: ["Selected surface", "Plane inliers"],
    symptoms: ["Support includes noisy out-of-band pixels", "Final support becomes much smaller than expected"],
    related: ["MAD k", "MAD floor", "Selected surface"],
  }),
  "detect_reference_surface.param.mad_k": help({
    title: "MAD k",
    summary: "Controls how wide the accepted Z/depth band is around the selected cluster median.",
    details: "Higher keeps more of the cluster; lower trims more aggressively. It only matters when MAD refinement is enabled.",
    consumes: "Selected cluster median and MAD spread.",
    produces: "Wider or narrower logical support band.",
    supportType: "Affects logical support and therefore downstream fit support.",
    whenToIncrease: "Increase it when true support pixels are being trimmed away and the final selected surface becomes too small.",
    whenToDecrease: "Decrease it when off-height or noisy pixels remain inside the final selected surface.",
    affects: ["Selected surface", "Plane inliers"],
    symptoms: ["Final support is too small", "Final support keeps noisy fringe pixels"],
    related: ["Refine by MAD", "MAD floor"],
  }),
  "detect_reference_surface.param.mad_floor": help({
    title: "MAD floor",
    summary: "Minimum robust spread used when the selected cluster appears very flat.",
    details: "This prevents the refinement band from becoming unrealistically narrow when the measured spread is near zero. It keeps the MAD-based trim from collapsing to an overly strict mask.",
    consumes: "MAD-based refinement statistics.",
    produces: "Floor on logical-support refinement width.",
    supportType: "Affects logical support before fit support.",
    whenToIncrease: "Increase it when very flat support produces an overly tiny final mask after refinement.",
    whenToDecrease: "Decrease it when the final support keeps too much off-height material despite a flat cluster.",
    affects: ["Selected surface", "Plane inliers"],
    symptoms: ["Nearly flat support collapses to a tiny mask", "Refinement stays too permissive on flat support"],
    related: ["Refine by MAD", "MAD k"],
  }),
  "detect_reference_surface.param.keep_border_support": help({
    title: "Keep border support",
    summary: "Preserves border-connected reference support that MAD refinement might otherwise remove.",
    details: "This is useful when true reference support touches the image border or ROI edge. It keeps those connected support regions available even if the trim step would otherwise cut them away.",
    consumes: "Refined support plus border connectivity.",
    produces: "Border-preserved logical support.",
    supportType: "Affects logical support.",
    whenToIncrease: "Enable it when valid border-connected belt support disappears after refinement.",
    whenToDecrease: "Disable it when border-connected noise keeps leaking into the final selected surface.",
    affects: ["Selected surface", "Fallback usage"],
    symptoms: ["Expected border support disappears", "Border noise remains in final support"],
    related: ["Selected blob cluster", "Selected surface"],
  }),
  "detect_reference_surface.param.blob_cluster_min_total_pixels": help({
    title: "Blob cluster min total pixels",
    summary: "Minimum acceptable size of the refined support mask.",
    details: "If the refined support falls below this size, fallback may be used instead of the trimmed cluster. It protects downstream fitting from tiny or unstable support masks.",
    consumes: "Refined support size.",
    produces: "Fallback decision boundary.",
    supportType: "Affects logical support fallback and downstream fit stability.",
    whenToIncrease: "Increase it when very small support masks are passing through and causing unstable fits.",
    whenToDecrease: "Decrease it when a valid but narrow support region is rejected as too small.",
    affects: ["Fallback decision", "Selected surface", "Plane fit stability"],
    symptoms: ["Fallback triggers because support is too small", "Tiny support survives and fit becomes unstable"],
    related: ["Blob fallback strategy", "Selected surface"],
  }),
  "detect_reference_surface.param.blob_fallback_strategy": help({
    title: "Blob fallback strategy",
    summary: "Determines which support mask is used if selected-cluster refinement fails or becomes too small.",
    details: "Fallback is a safety path for cases where the chosen blob cluster cannot produce a stable final support mask. The strategy controls which alternative support source replaces it.",
    consumes: "Refinement failure state and fallback configuration.",
    produces: "Replacement logical support mask.",
    supportType: "Affects logical support and downstream fit support indirectly.",
    affects: ["Selected surface", "Plane inliers", "Reference-model stability"],
    symptoms: ["Selected surface differs sharply from the chosen cluster", "A run succeeds only because fallback replaces the selected cluster"],
    related: ["Blob cluster min total pixels", "Selected surface"],
  }),
  "detect_reference_surface.param.background_detection_strategy": help({
    title: "Support selection",
    summary: "Chooses the overall reference-support strategy path.",
    details: "This is the top-level mode switch for Detect Reference. It changes which subprocesses run and which artifacts become authoritative.",
    consumes: "Valid ROI, heightmap, and strategy-specific reference parameters.",
    produces: "A logical-support strategy path plus its diagnostics.",
    supportType: "Affects logical support first, then every downstream fit-support and suppression decision.",
    fragmentedGuidance: "For fragmented belt scans, blob-height-cluster flow usually gives the most targeted controls because you can explicitly split and merge fragments.",
    mergedGuidance: "If object and belt are merged, choose a strategy that exposes the separation controls you need rather than over-tuning a simpler path.",
    overTuningRisk: "Switching strategies to fix one edge case can trade a local win for a less explainable pipeline overall.",
    optionDetails: [
      { value: "low_gradient_depth_plateaus", label: "Low-gradient depth plateaus", description: "Ranks low-gradient plateaus directly. Simpler path with fewer internal fragment controls." },
      { value: "low_gradient_surface", label: "Low-gradient surface", description: "Uses a flatter low-gradient support path without the full blob-cluster split flow." },
      { value: "low_gradient_bg_and_stripes", label: "Low-gradient background + stripes", description: "Belt background is used for height correction. Belt stripes are suppressed but excluded from background fitting. Unknown low-gradient patches are preserved for object detection." },
      { value: "low_gradient_blob_height_clusters", label: "Blob height clusters", description: "Builds components, optional splits, merges, and clusters before selecting support. Best for diagnosing fragmented or merged belt/object cases." },
      { value: "depth_percentile_plane", label: "Percentile / legacy", description: "Older percentile-driven path retained for compatibility and comparison." },
    ],
  }),
  "detect_reference_surface.param.gradient_threshold_mode": help({
    title: "Low-gradient threshold mode",
    summary: "Controls how the low-gradient cutoff is derived.",
    details: "This chooses whether the low-gradient gate uses a manual absolute cutoff, a percentile of the current gradient distribution, or Otsu thresholding.",
    consumes: "Gradient magnitude histogram.",
    produces: "Low-gradient candidate threshold.",
    supportType: "Affects logical support.",
    optionDetails: [
      { value: "percentile", label: "Percentile", description: "Adapts to the current scan by selecting the lowest-gradient fraction of pixels." },
      { value: "fixed", label: "Fixed", description: "Uses a manually chosen absolute gradient cutoff." },
      { value: "otsu", label: "Otsu", description: "Chooses a threshold from the gradient histogram automatically when the histogram separates cleanly." },
    ],
  }),
  "detect_reference_surface.param.gradient_threshold_value": help({
    title: "Low-gradient threshold value",
    summary: "Absolute cutoff used only when low-gradient threshold mode is fixed.",
    details: "Pixels calmer than this value remain eligible for support; stronger local variation is rejected.",
    consumes: "Gradient magnitude values.",
    produces: "Logical-support candidate gate.",
    supportType: "Affects logical support.",
  }),
  "detect_reference_surface.param.blob_component_mode": help({
    title: "Blob component mode",
    summary: "Chooses how low-gradient pixels are grouped into components before clustering or splitting.",
    details: "XY-only uses image-plane connectivity alone. Height-aware mode also considers local Z consistency.",
    consumes: "Low-gradient candidates plus connectivity and optional Z checks.",
    produces: "Connectivity-level candidate components.",
    supportType: "Connectivity-only leading into logical support.",
    fragmentedGuidance: "If belt support is over-fragmented in height-aware mode, the Z rules may be too strict.",
    mergedGuidance: "If object and belt are merged in XY-only mode, height-aware mode often separates them better.",
    overTuningRisk: "Switching modes without matching the related Z tolerances can create inconsistent behavior.",
    optionDetails: [
      { value: "xy_only", label: "XY only", description: "Groups neighboring low-gradient pixels by image connectivity without enforcing Z agreement." },
      { value: "height_aware", label: "Height aware", description: "Groups neighboring pixels only when connectivity and local height consistency both agree." },
    ],
  }),
  "detect_reference_surface.param.blob_split_method": help({
    title: "Split method",
    summary: "Chooses whether and how mixed blobs are split before clustering.",
    details: "This determines whether components stay intact, split from border cues, split from histograms, or use both in sequence.",
    consumes: "Candidate components and optional border/histogram diagnostics.",
    produces: "Logical-support fragments for clustering.",
    supportType: "Affects logical support.",
    fragmentedGuidance: "If the belt is already too fragmented, simpler or disabled splitting may be safer until you confirm the detector is stable.",
    mergedGuidance: "If object and belt remain fused, a split-capable mode is required before clustering can separate them.",
    overTuningRisk: "Choosing a complex split path to fix one sample can create unnecessary failure modes elsewhere.",
    optionDetails: [
      { value: "disabled", label: "Disabled", description: "Keeps each candidate component intact with no internal splitting." },
      { value: "height_borders", label: "Height borders", description: "Splits components from internally detected height-boundary cuts." },
      { value: "histogram_gap", label: "Histogram gap", description: "Splits components from per-blob height histogram gaps." },
      { value: "height_borders_then_histogram", label: "Height borders then histogram", description: "Uses border cuts first, then optional histogram refinement on the resulting pieces." },
    ],
  }),
  "detect_reference_surface.param.blob_split_height_border_mode": help({
    title: "Height-border mode",
    summary: "Chooses how local height-border strength is computed inside each candidate blob.",
    details: "Different detectors emphasize different kinds of internal transitions. The best choice depends on whether the belt texture is smooth, ribbed, or dominated by local range changes.",
    consumes: "Local height neighborhoods inside eligible blobs.",
    produces: "Height-border strength map.",
    supportType: "Diagnostics that drive logical-support splitting.",
    fragmentedGuidance: "If texture noise is fragmenting the belt, prefer the mode that suppresses weak repetitive texture on your scans.",
    mergedGuidance: "If the real object boundary is not showing up, switch to the mode that makes that transition stand out more clearly.",
    overTuningRisk: "Changing detector mode can help one material pattern while hurting another, so validate across multiple scans.",
    optionDetails: [
      { value: "sobel_gradient", label: "Sobel gradient", description: "Uses directional gradients to emphasize sharp local slopes and edge-like transitions." },
      { value: "local_range", label: "Local range", description: "Measures local max-min spread, which can reveal broader height jumps but may react to texture." },
      { value: "morphological_gradient", label: "Morphological gradient", description: "Uses local dilation-erosion difference for robust boundary strength on thicker transitions." },
    ],
  }),
  "detect_reference_surface.param.blob_split_height_border_threshold_mode": help({
    title: "Height-border threshold mode",
    summary: "Decides how strong a border response must be before it can cut a candidate blob.",
    details: "This mode turns the border-strength map into actual split candidates. It strongly controls whether the splitter is conservative or aggressive.",
    consumes: "Height-border strength distribution.",
    produces: "Accepted cut mask that drives logical-support fragments.",
    supportType: "Affects logical support through split acceptance.",
    fragmentedGuidance: "If belt texture is splitting the support, use a stricter threshold so only stronger borders become cuts.",
    mergedGuidance: "If object and belt stay merged, use a more sensitive threshold so the real boundary survives.",
    overTuningRisk: "A threshold that looks perfect on one scan can fail badly when the belt texture distribution shifts.",
    optionDetails: [
      { value: "fixed", label: "Fixed", description: "Uses a manually configured absolute threshold on the height-border strength map. Predictable but requires knowing a good cutoff. Too low causes belt texture to split; too high misses real object boundaries." },
      { value: "percentile", label: "Percentile", description: "Computes the threshold from the current border-strength distribution. Higher percentile means fewer/stronger cuts; lower percentile means more sensitive splitting. Recommended first for variable belt scans." },
      { value: "otsu", label: "Otsu", description: "Automatically selects a threshold from the border-strength histogram by separating weak and strong responses. Useful when the histogram is clearly bimodal, but can be unstable if chevron/rib texture dominates." },
    ],
  }),
  "detect_reference_surface.param.blob_split_height_border_percentile": help({
    title: "Height-border percentile",
    summary: "Percentile cutoff used when height-border threshold mode is percentile.",
    details: "Only border responses above this percentile become split candidates.",
    consumes: "Current border-strength distribution.",
    produces: "Accepted-cut sensitivity.",
    supportType: "Affects logical support through split acceptance.",
    fragmentedGuidance: "Raise it when weak belt texture is creating too many cuts.",
    mergedGuidance: "Lower it when object and belt remain fused because only very strong borders survive.",
    overTuningRisk: "Too high misses true boundaries; too low turns texture into cuts and creates support shards.",
  }),
  "detect_reference_surface.param.blob_split_height_border_min_delta_mm": help({
    title: "Height-border min delta",
    summary: "Minimum height change required before a border response is considered meaningful.",
    details: "This rejects weak local height transitions even if they are spatially coherent.",
    consumes: "Local height differences across candidate borders.",
    produces: "Filtered cut candidates.",
    supportType: "Affects logical support through split acceptance.",
    fragmentedGuidance: "Raise it when shallow belt texture is being mistaken for true internal boundaries.",
    mergedGuidance: "Lower it when the object/belt boundary is real but not tall enough to pass the current cutoff.",
    overTuningRisk: "A too-large delta hides subtle real boundaries; a too-small delta promotes texture-driven splitting.",
  }),
  "detect_reference_surface.param.blob_split_height_border_smoothing_kernel": help({
    title: "Height-border smoothing kernel",
    summary: "Smoothing applied before border strength is measured.",
    details: "Larger kernels suppress noise and repetitive texture but can also wash out narrow real boundaries.",
    consumes: "Local height neighborhoods before border extraction.",
    produces: "Smoothed border-strength input.",
    supportType: "Diagnostics that shape logical-support splitting.",
    fragmentedGuidance: "Raise it when fine belt texture produces noisy border responses.",
    mergedGuidance: "Lower it when real object edges are being blurred away and the splitter misses them.",
    overTuningRisk: "Too much smoothing hides useful boundaries; too little makes texture dominate the detector.",
  }),
  "detect_reference_surface.param.blob_split_height_border_min_length_px": help({
    title: "Height-border min edge length",
    summary: "Shortest accepted border segment that is allowed to create a cut.",
    details: "This discards tiny isolated border segments that are unlikely to represent a meaningful split.",
    consumes: "Thresholded border segments.",
    produces: "Longer, cleaner accepted cuts.",
    supportType: "Affects logical support through cut acceptance.",
    fragmentedGuidance: "Raise it when short texture streaks are fragmenting the belt.",
    mergedGuidance: "Lower it when the true object/belt boundary is short or partially visible and never survives to splitting.",
    overTuningRisk: "Too high erases small but real boundaries; too low promotes cut noise and tiny fragments.",
  }),
  "detect_reference_surface.param.blob_split_min_fragment_area_px": help({
    title: "Split min fragment area",
    summary: "Minimum fragment size that survives after splitting.",
    details: "This area gate removes tiny fragments that are unlikely to be stable support candidates.",
    consumes: "Split fragments after border or histogram segmentation.",
    produces: "Filtered logical-support fragments.",
    supportType: "Affects logical support.",
    fragmentedGuidance: "Lower it when narrow but valid belt fragments disappear immediately after splitting.",
    mergedGuidance: "Raise it when spurious tiny fragments clutter clustering without helping separation.",
    overTuningRisk: "Too low floods clustering with noise; too high removes legitimate thin support strips.",
  }),
  "detect_reference_surface.param.blob_split_merge_weak_boundaries": help({
    title: "Merge weak boundaries",
    summary: "Allows the pipeline to reconnect fragments separated by weak, likely non-meaningful cuts.",
    details: "This rescue step is meant for false-positive splits, especially along textured belt structure.",
    consumes: "Split fragments plus boundary-strength and Z-gap checks.",
    produces: "Merged logical-support fragments.",
    supportType: "Affects logical support and connectivity only.",
    fragmentedGuidance: "Enable it when valid belt fragments should reconnect after over-splitting.",
    mergedGuidance: "Disable it or tighten its thresholds when object and belt are being re-fused incorrectly.",
    overTuningRisk: "Overusing rescue merges can undo the very split that was separating object from belt.",
  }),
  "detect_reference_surface.param.blob_split_merge_max_median_z_gap_mm": help({
    title: "Merge max median Z gap",
    summary: "Largest allowed median height gap between fragments for weak-boundary rescue.",
    details: "Fragments farther apart in height than this are not allowed to merge back together.",
    consumes: "Per-fragment median height comparison.",
    produces: "Merge eligibility.",
    supportType: "Affects logical support and connectivity only.",
    fragmentedGuidance: "Raise it slightly when valid belt fragments differ a little in height but should still reconnect.",
    mergedGuidance: "Lower it when object fragments are getting merged back into the belt.",
    overTuningRisk: "A large gap tolerance can reconnect physically different surfaces that only happen to be nearby.",
  }),
  "detect_reference_surface.param.blob_split_merge_max_boundary_strength_mm": help({
    title: "Merge max boundary strength",
    summary: "Strongest allowed separating boundary that still counts as weak enough to merge across.",
    details: "Lower values require the split boundary to be very weak before rescue is allowed.",
    consumes: "Boundary-strength measurement between neighboring fragments.",
    produces: "Merge eligibility.",
    supportType: "Affects logical support and connectivity only.",
    fragmentedGuidance: "Raise it slightly when the belt split was caused by weak texture and should be ignored.",
    mergedGuidance: "Lower it when real object boundaries are being treated as weak and merged away.",
    overTuningRisk: "If this is too permissive, the rescue step can destroy useful object/belt separation.",
  }),
  "detect_reference_surface.param.blob_split_merge_background_like_only": help({
    title: "Merge background-like only",
    summary: "Restricts weak-boundary rescue to fragments that still look like background/reference support.",
    details: "This is a safety guard that prevents the merge rescue from rejoining fragments unless both sides still resemble support.",
    consumes: "Fragment appearance/support heuristics plus weak-boundary checks.",
    produces: "Safer merge decisions.",
    supportType: "Affects logical support and connectivity only.",
    fragmentedGuidance: "Disable only if valid support fragments fail to reconnect despite clearly belonging to the belt.",
    mergedGuidance: "Enable it when object fragments are being merged back into support.",
    overTuningRisk: "Turning it off makes merge rescue more flexible but also much riskier for object contamination.",
  }),
  "detect_reference_surface.param.reference_surface_model": help({
    title: "Reference model",
    summary: "Chooses what surface model should explain the selected support.",
    details: "This setting controls whether the pipeline fits a plane, uses a constant-Z surface, or resolves automatically.",
    consumes: "Selected support and model-fit configuration.",
    produces: "Fit-support interpretation, residual diagnostics, and inlier mask behavior.",
    supportType: "Affects fit support and diagnostics.",
    fragmentedGuidance: "If fragmented but valid support is failing plane QA, a simpler model can be more stable than just loosening thresholds.",
    mergedGuidance: "If object contamination is slight, a stricter model can sometimes reject it from fit support.",
    overTuningRisk: "Changing the model can improve one geometry while degrading normalization quality elsewhere.",
    optionDetails: [
      { value: "auto", label: "Auto", description: "Chooses the model at rerun time from the current run state and support quality." },
      { value: "plane", label: "Plane", description: "Fits a planar reference surface and uses residuals to validate support." },
      { value: "constant_z", label: "Constant Z", description: "Uses a flat constant-height reference, often more tolerant when support is fragmented or plane fit is unstable." },
    ],
  }),
  "detect_reference_surface.group.belt_stripe_suppression": help({
    title: "Belt stripe suppression",
    summary: "Removes raised belt texture (chevron ribs, raised ribs) from reference support before model fitting.",
    details: "Method: two-pass morphological stripe detection on the heightmap inside the search domain (full fit ROI or background plateau only), then subtract detected stripe pixels from the incoming refined support mask.\n\nPass 1 — altitude top-hat: a local-min baseline is computed with a morphological window sized in millimetres (baseline = erode(z); altitude = z − baseline for raised ribs). Narrow raised ribs narrower than the window survive as positive altitude. With direction=auto, both raised and recessed variants are tried and the one with the clearer tail (p95 − p50 spread) wins. Altitude is thresholded with Otsu, k·MAD, or a fixed mm cutoff (never below the minimum altitude floor).\n\nPass 2 — shape / z-floor (optional): estimates an upper belt-height reference from the background plateau, flags pixels above belt + margin but below a max stripe height, closes small gaps, then uses a wide binary opening to keep object-sized structures and label remaining above-belt pixels as stripe candidates. This catches wide ribs and object-adjacent texture that the narrow top-hat window can miss.\n\nFinal merge: stripe mask = top-hat candidates ∪ shape candidates. If the stripe fraction is below the minimum stripe fraction, the filter is skipped and support is unchanged. Otherwise stripe pixels are removed to produce belt-base / stripe-filtered support for downstream fitting.",
    consumes: "Refined selected-cluster support mask and heightmap Z values within the chosen search scope.",
    produces: "Stripe-filtered support, belt base mask, and diagnostic masks (top-hat, shape, above-belt, wide-object).",
    affects: ["Pre-stripe support", "Belt stripes", "Removed by stripe suppression", "Stripe-filtered support", "Selected support"],
    symptoms: ["Valid belt support disappears after stripe filtering", "Visible belt ribs remain in support", "Objects get flagged as stripes"],
    related: ["Pre-stripe support", "Belt stripes — top-hat", "Belt stripes — shape", "Stripe-filtered support"],
  }),
  "detect_reference_surface.group.stripe_input": help({
    title: "Input / support handoff",
    summary: "Controls when stripe suppression runs and how broadly it searches.",
    details: "These controls gate the stripe filter on the incoming refined support. Enable suppression when belt ribs or raised texture contaminate fit support. Scope=global searches the full fit ROI; scope=background plateau limits detection to the selected plateau when global search overreaches into objects. The underlying method is morphological top-hat altitude detection plus an optional shape/z-floor pass — see Belt stripe suppression help for the full algorithm.",
    consumes: "Refined selected-cluster support mask.",
    produces: "Stripe-filtered support and stripe-removal diagnostics.",
    affects: ["Pre-stripe support", "Removed by stripe suppression", "Stripe-filtered support"],
  }),
  "detect_reference_surface.param.belt_stripe_filter_enabled": help({
    title: "Suppress belt stripes",
    summary: "Enables stripe detection and removal from reference support.",
    details: "When enabled, the pipeline searches for raised belt texture and removes it from fit support.",
    affects: ["Belt stripes mask", "Removed by stripe filter", "Stripe-filtered support"],
    whenToDecrease: "Disable only when stripe suppression is removing real flat support instead of texture.",
  }),
  "detect_reference_surface.param.belt_stripe_filter_scope": help({
    title: "Stripe detection scope",
    summary: "Controls how broadly stripe detection searches relative to incoming support.",
    details: "Global search covers the full fit ROI. Background-plateau scope limits search to the selected background plateau when global search overreaches.",
    affects: ["Belt stripes mask", "Pre-stripe support"],
    optionDetails: [
      { value: "global", label: "Global", description: "Search for stripes across the full fit region." },
      { value: "bg_plateau", label: "Background plateau", description: "Limit stripe search to the selected background plateau only." },
    ],
  }),
  "detect_reference_surface.artifact.pre_stripe_support": help({
    title: "Pre-stripe support",
    summary: "Selected reference support before stripe suppression.",
    details: "This is the refined support mask that enters the stripe filter. Compare it against stripe-filtered support and removed-by-stripe masks to see what changed.",
    affects: ["Stripe-filtered support", "Removed by stripe suppression"],
  }),
  "detect_reference_surface.artifact.belt_baseline": help({
    title: "Local-min baseline",
    summary: "Estimated local belt baseline used to detect raised stripe-like structures.",
    details: "The stripe filter computes a local-min baseline (erode) over the search domain. Altitude evidence is measured relative to this surface.",
    affects: ["Stripe altitude", "Stripes — top-hat"],
  }),
  "detect_reference_surface.artifact.belt_altitude_plot": help({
    title: "Stripe altitude",
    summary: "Height/altitude evidence above the local belt baseline.",
    details: "Shows the altitude distribution used to threshold stripe candidates during the top-hat pass.",
    affects: ["Stripes — top-hat", "Belt stripes"],
  }),
  "detect_reference_surface.artifact.belt_stripes_tophat": help({
    title: "Stripes — top-hat",
    summary: "Morphology/top-hat response highlighting narrow raised stripe candidates.",
    details: "First-pass stripe candidates from local baseline subtraction and altitude thresholding.",
    affects: ["Belt stripes", "Removed by stripe suppression"],
  }),
  "detect_reference_surface.artifact.belt_stripes_shape": help({
    title: "Stripes — shape pass",
    summary: "Stripe candidates that passed shape/geometry constraints.",
    details: "Optional second pass that catches wider raised ribs and object-adjacent texture missed by the narrow top-hat window.",
    affects: ["Belt stripes", "Above belt mask", "Wide-object mask"],
  }),
  "detect_reference_surface.artifact.belt_wide_object": help({
    title: "Wide-object mask",
    summary: "Mask used to avoid treating wide object-like structures as belt stripes.",
    details: "Object-sized regions above the belt reference are excluded from the shape stripe pass.",
    affects: ["Stripes — shape pass", "Belt stripes"],
  }),
  "detect_reference_surface.artifact.belt_above_belt": help({
    title: "Above belt mask",
    summary: "Pixels considered above the belt/reference baseline.",
    details: "Intermediate gating mask for the shape pass before wide-object suppression.",
    affects: ["Stripes — shape pass", "Wide-object mask"],
  }),
  "detect_reference_surface.artifact.belt_base": help({
    title: "Belt base",
    summary: "Support classified as stable belt/base after stripe reasoning.",
    details: "Decision mask for pixels kept as belt base after stripe candidates are identified.",
    affects: ["Belt stripes", "Stripe-filtered support"],
  }),
  "detect_reference_surface.artifact.belt_stripes": help({
    title: "Belt stripes",
    summary: "Final stripe mask detected by the stripe filter.",
    details: "Union of top-hat and shape stripe candidates that were removed from support.",
    affects: ["Removed by stripe suppression", "Stripe-filtered support"],
  }),
  "detect_reference_surface.artifact.removed_by_stripe_filter": help({
    title: "Removed by stripe suppression",
    summary: "Pixels removed from support due to stripe suppression.",
    details: "Shows exactly which support pixels the stripe filter rejected before downstream reference fitting.",
    affects: ["Stripe-filtered support", "Selected support"],
  }),
  "detect_reference_surface.artifact.stripe_filtered_support": help({
    title: "Stripe-filtered support",
    summary: "Cleaned reference support passed to later reference fitting and support selection.",
    details: "This is the substage output handed downstream after stripe pixels are removed from pre-stripe support.",
    affects: ["Selected support", "Reference model support"],
  }),
  "detect_reference_surface.param.reference_suppression_mask_policy": help({
    title: "Suppression mask policy",
    summary: "Chooses which support-derived mask downstream segmentation should suppress.",
    details: "This policy determines whether segmentation removes the selected support, a broader expanded support, or only final model inliers.",
    consumes: "Selected support, fit support, and downstream segmentation handoff rules.",
    produces: "Reference suppression mask.",
    supportType: "Affects suppression mask only.",
    fragmentedGuidance: "If fragmented belt leaks into segmentation, choose a policy that preserves enough real support coverage.",
    mergedGuidance: "If the object is being suppressed, use the narrowest trustworthy support source and clean the support earlier.",
    overTuningRisk: "Policy changes can hide upstream support errors instead of fixing them.",
    optionDetails: [
      { value: "auto", label: "Auto", description: "Resolves the suppression source automatically from the chosen reference method and run state." },
      { value: "selected_support", label: "Selected support", description: "Uses the final logical support mask directly for suppression." },
      { value: "expanded_support", label: "Expanded/model support", description: "Uses a broader expanded support source, which can suppress more belt area but is riskier near objects." },
      { value: "final_model_inliers", label: "Final model inliers", description: "Uses only fit-validated inliers, usually the safest but sometimes too sparse on fragmented belts." },
    ],
  }),
};

const SUBSTAGE_HELP_KEYS: Record<string, string> = {
  gradient: "detect_reference_surface.process.gradient_low_gradient",
  component_formation: "detect_reference_surface.process.component_formation",
  height_border_detection: "detect_reference_surface.process.height_border_detection",
  blob_splitting: "detect_reference_surface.process.blob_splitting",
  fragment_merge: "detect_reference_surface.process.fragment_merge",
  height_clustering: "detect_reference_surface.process.height_clustering",
  cluster_scoring: "detect_reference_surface.process.cluster_scoring",
  selected_support: "detect_reference_surface.process.selected_surface",
  reference_model: "detect_reference_surface.process.reference_model",
  stripes: "detect_reference_surface.group.belt_stripe_suppression",
};

const GROUP_HELP_KEYS: Record<string, string> = {
  stripe_suppression: "detect_reference_surface.group.belt_stripe_suppression",
  stripe_input: "detect_reference_surface.group.stripe_input",
  "Belt stripe suppression": "detect_reference_surface.group.belt_stripe_suppression",
  "Input / support handoff": "detect_reference_surface.group.stripe_input",
};

const VIEW_HELP_KEYS: Record<string, string> = {
  pre_stripe_support: "detect_reference_surface.artifact.pre_stripe_support",
  belt_baseline: "detect_reference_surface.artifact.belt_baseline",
  belt_altitude_plot: "detect_reference_surface.artifact.belt_altitude_plot",
  belt_stripes_tophat: "detect_reference_surface.artifact.belt_stripes_tophat",
  belt_stripes_shape: "detect_reference_surface.artifact.belt_stripes_shape",
  belt_wide_object: "detect_reference_surface.artifact.belt_wide_object",
  belt_above_belt: "detect_reference_surface.artifact.belt_above_belt",
  belt_base: "detect_reference_surface.artifact.belt_base",
  belt_stripes: "detect_reference_surface.artifact.belt_stripes",
  removed_by_stripe_filter: "detect_reference_surface.artifact.removed_by_stripe_filter",
  stripe_filtered_support: "detect_reference_surface.artifact.stripe_filtered_support",
  selected_blob_cluster: "detect_reference_surface.artifact.selected_blob_cluster",
  selected_support_lineage: "detect_reference_surface.process.selected_support_lineage",
  height_border_fragments: "detect_reference_surface.artifact.height_border_fragments",
  height_split_blobs: "detect_reference_surface.artifact.height_split_blobs",
  selected_surface: "detect_reference_surface.artifact.selected_surface",
  reference_model_support: "detect_reference_surface.artifact.reference_model_support",
  plane_inliers: "detect_reference_surface.artifact.plane_inliers",
  reference_suppression_mask: "detect_reference_surface.artifact.reference_suppression_mask",
  residual_heatmap: "detect_reference_surface.artifact.residuals",
  residual_histogram: "detect_reference_surface.artifact.residuals",
};

const PARAM_HELP_KEYS: Record<string, string> = {
  background_detection_strategy: "detect_reference_surface.param.background_detection_strategy",
  gradient_threshold_mode: "detect_reference_surface.param.gradient_threshold_mode",
  gradient_threshold_value: "detect_reference_surface.param.gradient_threshold_value",
  blob_component_mode: "detect_reference_surface.param.blob_component_mode",
  blob_split_method: "detect_reference_surface.param.blob_split_method",
  blob_split_height_border_mode: "detect_reference_surface.param.blob_split_height_border_mode",
  blob_split_height_border_threshold_mode: "detect_reference_surface.param.blob_split_height_border_threshold_mode",
  blob_split_height_border_percentile: "detect_reference_surface.param.blob_split_height_border_percentile",
  blob_split_height_border_min_delta_mm: "detect_reference_surface.param.blob_split_height_border_min_delta_mm",
  blob_split_height_border_smoothing_kernel: "detect_reference_surface.param.blob_split_height_border_smoothing_kernel",
  blob_split_height_border_min_length_px: "detect_reference_surface.param.blob_split_height_border_min_length_px",
  blob_split_min_fragment_area_px: "detect_reference_surface.param.blob_split_min_fragment_area_px",
  blob_split_merge_weak_boundaries: "detect_reference_surface.param.blob_split_merge_weak_boundaries",
  blob_split_merge_max_median_z_gap_mm: "detect_reference_surface.param.blob_split_merge_max_median_z_gap_mm",
  blob_split_merge_max_boundary_strength_mm: "detect_reference_surface.param.blob_split_merge_max_boundary_strength_mm",
  blob_split_merge_background_like_only: "detect_reference_surface.param.blob_split_merge_background_like_only",
  reference_surface_model: "detect_reference_surface.param.reference_surface_model",
  reference_suppression_mask_policy: "detect_reference_surface.param.reference_suppression_mask_policy",
  blob_cluster_refine_by_mad: "detect_reference_surface.param.refine_by_mad",
  blob_cluster_refine_mad_k: "detect_reference_surface.param.mad_k",
  blob_cluster_refine_floor_mm: "detect_reference_surface.param.mad_floor",
  blob_cluster_refine_keep_border_support: "detect_reference_surface.param.keep_border_support",
  blob_cluster_min_total_pixels: "detect_reference_surface.param.blob_cluster_min_total_pixels",
  blob_cluster_fallback_strategy: "detect_reference_surface.param.blob_fallback_strategy",
  belt_stripe_filter_enabled: "detect_reference_surface.param.belt_stripe_filter_enabled",
  belt_stripe_filter_scope: "detect_reference_surface.param.belt_stripe_filter_scope",
};

const ARTIFACT_ROLE_HELP_KEYS: Record<string, string> = {
  logical_support: "detect_reference_surface.role.logical_support",
  fit_support: "detect_reference_surface.role.fit_support",
  suppression_mask: "detect_reference_surface.role.suppression_mask",
  connectivity_support: "detect_reference_surface.role.connectivity_support",
  diagnostic: "detect_reference_surface.role.diagnostic",
};

const DISPLAY_ROLE_HELP_KEYS: Record<string, string> = {
  selected_reference_surface: "detect_reference_surface.role.logical_support",
  fit_support: "detect_reference_surface.role.fit_support",
  strategy_intermediate: "detect_reference_surface.role.logical_support",
  qa: "detect_reference_surface.role.diagnostic",
  debug: "detect_reference_surface.role.diagnostic",
};

const LINEAGE_SUMMARY_HELP_KEYS: Record<string, string> = {
  "Selected support": "detect_reference_surface.artifact.selected_surface",
  "Model support": "detect_reference_surface.artifact.reference_model_support",
  "Suppression mask": "detect_reference_surface.artifact.reference_suppression_mask",
};

export function resolveStudioHelpEntry(key: string | null | undefined): StudioHelpEntry | null {
  if (!key) return null;
  return STUDIO_HELP_CONTENT[key] ?? null;
}

export function detectReferenceSubstageHelpKey(substageId: string | null | undefined): string | null {
  if (!substageId) return null;
  return SUBSTAGE_HELP_KEYS[substageId] ?? null;
}

export function detectReferenceGroupHelpKey(groupId: string | null | undefined): string | null {
  if (!groupId) return null;
  return GROUP_HELP_KEYS[groupId] ?? null;
}

export function detectReferenceViewHelpKey(viewId: string | null | undefined): string | null {
  if (!viewId) return null;
  return VIEW_HELP_KEYS[viewId] ?? null;
}

export function detectReferenceParamHelpKey(paramKey: string | null | undefined): string | null {
  if (!paramKey) return null;
  return PARAM_HELP_KEYS[paramKey] ?? null;
}

export function detectReferenceArtifactRoleHelpKey(role: string | null | undefined): string | null {
  if (!role) return null;
  return ARTIFACT_ROLE_HELP_KEYS[role] ?? null;
}

export function detectReferenceDisplayRoleHelpKey(role: string | null | undefined): string | null {
  if (!role) return null;
  return DISPLAY_ROLE_HELP_KEYS[role] ?? null;
}

export function detectReferenceLineageSummaryHelpKey(label: string | null | undefined): string | null {
  if (!label) return null;
  return LINEAGE_SUMMARY_HELP_KEYS[label] ?? null;
}
