from __future__ import annotations

from dataclasses import dataclass, field
from typing import Any

from vision_3d_acquisition.ml.features.schemas import FEATURE_COLUMNS


@dataclass(frozen=True)
class FeatureDefinition:
    feature_key: str
    display_name: str
    family: str
    family_label: str
    source_stage: str
    unit: str | None
    formula: str
    algorithm_summary: str
    inputs: tuple[str, ...]
    interpretation: str
    caveats: tuple[str, ...] = ()
    stable_schema: bool = False
    diagnostic_only: bool = False
    experimental: bool = False
    higher_is_worse: bool | None = None
    expected_range: tuple[float, float] | None = None
    display_precision: int | None = None
    preferred_chart_scale: str = "linear"
    studio_stage: str | None = None
    source_metric_path: str = ""
    legacy_aliases: tuple[str, ...] = ()
    extraction_paths: tuple[str, ...] = field(default_factory=tuple)

    def payload(self) -> dict[str, Any]:
        return {
            "key": self.feature_key,
            "feature_key": self.feature_key,
            "display_name": self.display_name,
            "semantic_group": self.family_label,
            "family": self.family,
            "family_label": self.family_label,
            "unit": self.unit,
            "description": self.algorithm_summary,
            "source_stage": self.source_stage,
            "source_metric_path": self.source_metric_path,
            "formula": self.formula,
            "algorithm_summary": self.algorithm_summary,
            "inputs": list(self.inputs),
            "interpretation": self.interpretation,
            "caveats": list(self.caveats),
            "stable_schema": self.stable_schema,
            "diagnostic_only": self.diagnostic_only,
            "experimental": self.experimental,
            "higher_is_worse": self.higher_is_worse,
            "expected_range": list(self.expected_range) if self.expected_range is not None else None,
            "display_precision": self.display_precision,
            "preferred_chart_scale": self.preferred_chart_scale,
            "studio_stage": self.studio_stage or self.source_stage,
            "legacy_aliases": list(self.legacy_aliases),
        }


FEATURE_REGISTRY: dict[str, FeatureDefinition] = {
    "feature_eccentricity": FeatureDefinition(
        feature_key="feature_eccentricity",
        display_name="Footprint eccentricity",
        family="footprint_geometry",
        family_label="Footprint geometry",
        source_stage="measurement",
        unit="ratio",
        formula="sqrt(1 - minor_axis_mm^2 / major_axis_mm^2)",
        algorithm_summary="Computed from the fitted 2D footprint ellipse over the segmented object mask.",
        inputs=("major_axis_mm", "minor_axis_mm", "segmented footprint ellipse"),
        interpretation="Higher values mean the 2D footprint is more elongated.",
        caveats=("Derived from a 2D footprint ellipse, not the full 3D visible surface.",),
        stable_schema=True,
        diagnostic_only=False,
        higher_is_worse=True,
        expected_range=(0.0, 1.0),
        display_precision=3,
        studio_stage="measurement",
        source_metric_path="objects[].feature_eccentricity",
        legacy_aliases=("Eccentricity", "ellipse eccentricity"),
        extraction_paths=("feature_eccentricity",),
    ),
    "footprint_roundness": FeatureDefinition(
        feature_key="footprint_roundness",
        display_name="Footprint roundness",
        family="footprint_geometry",
        family_label="Footprint geometry",
        source_stage="measurement",
        unit="ratio",
        formula="4 * pi * area / perimeter^2",
        algorithm_summary="2D roundness/circularity-style score derived from the segmented object footprint.",
        inputs=("footprint area", "footprint perimeter"),
        interpretation="Higher values mean the visible 2D footprint is more circle-like.",
        caveats=("This reflects 2D footprint geometry and should not be interpreted as a direct 3D sphere quality metric.",),
        stable_schema=True,
        diagnostic_only=False,
        higher_is_worse=False,
        expected_range=(0.0, 1.0),
        display_precision=3,
        studio_stage="measurement",
        source_metric_path="objects[].feature_footprint_roundness",
        legacy_aliases=("feature_footprint_roundness", "Footprint roundness"),
        extraction_paths=("feature_footprint_roundness", "footprint_roundness", "sphericity_score"),
    ),
    "feature_footprint_roundness": FeatureDefinition(
        feature_key="feature_footprint_roundness",
        display_name="Footprint roundness (raw)",
        family="footprint_geometry",
        family_label="Footprint geometry",
        source_stage="measurement",
        unit="ratio",
        formula="4 * pi * area / perimeter^2",
        algorithm_summary="Raw per-object roundness emitted in processed object rows before Feature Analytics normalization aliases.",
        inputs=("footprint area", "footprint perimeter"),
        interpretation="Higher values mean the visible 2D footprint is more circle-like.",
        caveats=("Raw object-row key retained for completeness. Prefer the normalized footprint_roundness view for audits unless the raw key is explicitly needed.",),
        stable_schema=False,
        diagnostic_only=True,
        higher_is_worse=False,
        expected_range=(0.0, 1.0),
        display_precision=3,
        studio_stage="measurement",
        source_metric_path="objects[].feature_footprint_roundness",
        legacy_aliases=("Footprint roundness raw",),
        extraction_paths=("feature_footprint_roundness",),
    ),
    "footprint_radial_cv": FeatureDefinition(
        feature_key="footprint_radial_cv",
        display_name="Radial boundary variation",
        family="footprint_geometry",
        family_label="Footprint geometry",
        source_stage="measurement",
        unit="ratio",
        formula="std(radius_to_contour_centroid) / mean(radius_to_contour_centroid)",
        algorithm_summary="Measures how much boundary radius varies around the footprint centroid.",
        inputs=("footprint contour", "centroid"),
        interpretation="Higher values mean a more irregular or lobed footprint boundary.",
        caveats=("2D footprint irregularity can come from segmentation artifacts as well as real object damage.",),
        stable_schema=True,
        diagnostic_only=False,
        higher_is_worse=True,
        expected_range=(0.0, 1.0),
        display_precision=3,
        studio_stage="measurement",
        source_metric_path="objects[].footprint_geometry.radial_cv",
        legacy_aliases=("radial_cv",),
        extraction_paths=("footprint_radial_cv", "footprint_geometry.radial_cv"),
    ),
    "height_max_mm": FeatureDefinition(
        feature_key="height_max_mm",
        display_name="Max height",
        family="height_metrics",
        family_label="Height metrics",
        source_stage="measurement",
        unit="mm",
        formula="max(height_above_belt_mm) over object pixels",
        algorithm_summary="Maximum normalized height above the detected reference surface inside the object mask.",
        inputs=("normalized heightmap", "object mask"),
        interpretation="Higher values indicate taller visible height peaks above the reference surface.",
        caveats=("Based on the visible 2.5D surface only and sensitive to calibration and segmentation quality.",),
        stable_schema=True,
        diagnostic_only=False,
        higher_is_worse=None,
        display_precision=2,
        studio_stage="measurement",
        source_metric_path="objects[].height_above_belt_mm.max_height_mm",
        legacy_aliases=("max_height_mm",),
        extraction_paths=("height_max_mm", "height_above_belt_mm.max_height_mm", "height_above_belt_mm.max"),
    ),
    "height_mean_mm": FeatureDefinition(
        feature_key="height_mean_mm",
        display_name="Mean height",
        family="height_metrics",
        family_label="Height metrics",
        source_stage="measurement",
        unit="mm",
        formula="mean(height_above_belt_mm) over object pixels",
        algorithm_summary="Average normalized height above the detected reference surface inside the object mask.",
        inputs=("normalized heightmap", "object mask"),
        interpretation="Higher values indicate a taller average visible height profile.",
        caveats=("Visible-surface average only; not a full volumetric or mass measurement.",),
        stable_schema=True,
        diagnostic_only=False,
        higher_is_worse=None,
        display_precision=2,
        studio_stage="measurement",
        source_metric_path="objects[].height_above_belt_mm.mean_height_mm",
        legacy_aliases=("mean_height_mm",),
        extraction_paths=("height_mean_mm", "height_above_belt_mm.mean_height_mm", "height_above_belt_mm.mean"),
    ),
    "height_p95_mm": FeatureDefinition(
        feature_key="height_p95_mm",
        display_name="P95 height",
        family="height_metrics",
        family_label="Height metrics",
        source_stage="measurement",
        unit="mm",
        formula="percentile(height_above_belt_mm, 95) over object pixels",
        algorithm_summary="95th percentile of normalized height above the reference surface inside the object mask.",
        inputs=("normalized heightmap", "object mask"),
        interpretation="Captures near-peak object height while being less sensitive than strict max height.",
        caveats=("Still sensitive to spikes and segmentation/calibration issues.",),
        stable_schema=True,
        diagnostic_only=False,
        higher_is_worse=None,
        display_precision=2,
        studio_stage="measurement",
        source_metric_path="objects[].height_above_belt_mm.p95_height_mm",
        legacy_aliases=("p95_height_mm",),
        extraction_paths=("height_p95_mm", "height_above_belt_mm.p95_height_mm"),
    ),
    "feature_volume_proxy_mm3": FeatureDefinition(
        feature_key="feature_volume_proxy_mm3",
        display_name="Heightmap volume proxy",
        family="volume_proxy",
        family_label="Volume / mass proxy",
        source_stage="measurement",
        unit="mm3",
        formula="sum(max(height_above_belt_mm, 0)) * pixel_area_mm2",
        algorithm_summary="Integrates visible normalized height over the segmented footprint to approximate above-belt volume.",
        inputs=("normalized heightmap", "object mask", "pixel area"),
        interpretation="Higher values indicate more visible material above the belt/reference plane.",
        caveats=("A 2.5D proxy from the visible surface, not true closed-object volume, mass, or density.",),
        stable_schema=True,
        diagnostic_only=False,
        higher_is_worse=None,
        display_precision=1,
        studio_stage="measurement",
        source_metric_path="objects[].feature_volume_proxy_mm3",
        legacy_aliases=("Volume proxy",),
        extraction_paths=("feature_volume_proxy_mm3",),
    ),
    "feature_sphericity_3d": FeatureDefinition(
        feature_key="feature_sphericity_3d",
        display_name="3D axis balance",
        family="surface_shape",
        family_label="Surface shape",
        source_stage="measurement",
        unit="ratio",
        formula="min(dim_x_mm, dim_y_mm, dim_z_mm) / max(dim_x_mm, dim_y_mm, dim_z_mm)",
        algorithm_summary="Compares canonical X/Y/Z physical extents after measurement-space corrections to estimate axis balance.",
        inputs=("dim_x_mm", "dim_y_mm", "dim_z_mm"),
        interpretation="1.0 means extents are balanced across X/Y/Z. Lower values indicate elongation, flattening, truncation, scale issues, or segmentation problems.",
        caveats=("This is not a true sphere-fit metric and does not directly measure surface curvature.",),
        stable_schema=True,
        diagnostic_only=False,
        higher_is_worse=False,
        expected_range=(0.0, 1.0),
        display_precision=3,
        studio_stage="measurement",
        source_metric_path="objects[].feature_sphericity_3d",
        legacy_aliases=("Sphericity 3D", "axis balance", "shape.sphericity_3d"),
        extraction_paths=("feature_sphericity_3d",),
    ),
    "feature_flatness": FeatureDefinition(
        feature_key="feature_flatness",
        display_name="Surface flatness score",
        family="surface_shape",
        family_label="Surface shape",
        source_stage="measurement",
        unit="score",
        formula="1 - std(max(height, 0)) / mean(max(height, 0))",
        algorithm_summary="Heuristic summary of how uniform the visible height distribution is across the segmented object.",
        inputs=("normalized heightmap", "object mask"),
        interpretation="Higher values mean the visible surface height distribution is more uniform; lower values indicate stronger height variation.",
        caveats=("This is a heuristic height-distribution score, not a true flat-plane fit.",),
        stable_schema=True,
        diagnostic_only=False,
        higher_is_worse=False,
        display_precision=3,
        studio_stage="measurement",
        source_metric_path="objects[].feature_flatness",
        legacy_aliases=("Flatness",),
        extraction_paths=("feature_flatness",),
    ),
    "feature_edge_roughness": FeatureDefinition(
        feature_key="feature_edge_roughness",
        display_name="Edge roughness",
        family="damage_metrics",
        family_label="Damage / deformation",
        source_stage="measurement",
        unit="mm",
        formula="1.4826 * median(|residual - median(residual)|)",
        algorithm_summary="Robust roughness estimate from high-frequency normalized-height residuals inside the eroded object interior.",
        inputs=("normalized height residual", "inner object mask"),
        interpretation="Higher values indicate rougher local surface or edge variation.",
        caveats=("Sensitive to segmentation boundaries and heightmap noise, not only physical surface damage.",),
        stable_schema=True,
        diagnostic_only=False,
        higher_is_worse=True,
        display_precision=3,
        studio_stage="measurement",
        source_metric_path="objects[].feature_edge_roughness",
        legacy_aliases=("Edge roughness",),
        extraction_paths=("feature_edge_roughness",),
    ),
    "fit_rmse_mm": FeatureDefinition(
        feature_key="fit_rmse_mm",
        display_name="Visible surface fit RMSE",
        family="sphere_consistency",
        family_label="Sphere consistency",
        source_stage="measurement",
        unit="mm",
        formula="RMSE of point-to-fit residuals over the visible object surface",
        algorithm_summary="Legacy fit residual field carried in object rows for compatibility with older exports.",
        inputs=("visible surface XYZ points", "fit residuals"),
        interpretation="Lower values indicate a better visible-surface geometric fit.",
        caveats=("Legacy key retained for compatibility. Prefer surface_sphere_fit_rmse_mm when available.",),
        stable_schema=True,
        diagnostic_only=False,
        higher_is_worse=True,
        display_precision=3,
        studio_stage="measurement",
        source_metric_path="objects[].fit_rmse_mm",
        legacy_aliases=("Surface fit RMSE",),
        extraction_paths=("fit_rmse_mm",),
    ),
    "surface_sphere_fit_rmse_mm": FeatureDefinition(
        feature_key="surface_sphere_fit_rmse_mm",
        display_name="Raw sphere-fit RMSE",
        family="sphere_consistency",
        family_label="Sphere consistency",
        source_stage="measurement",
        unit="mm",
        formula="Least-squares sphere fit over visible object XYZ points; RMSE of point-to-sphere residuals",
        algorithm_summary="Fits a sphere to visible 2.5D surface points and reports the residual RMSE in millimeters.",
        inputs=("visible object XYZ points", "sphere fit residuals"),
        interpretation="Lower values mean the visible surface fits a sphere better in absolute millimeters.",
        caveats=(
            "Raw RMSE is scale-dependent and visible-surface-only; prefer normalized residuals and sphere plausibility for classification.",
            "Computed over the visible 2.5D surface only, not a full 3D scan of the object.",
        ),
        stable_schema=True,
        diagnostic_only=False,
        higher_is_worse=True,
        display_precision=3,
        studio_stage="measurement",
        source_metric_path="objects[].surface_geometry.sphere_fit_rmse_mm",
        legacy_aliases=("sphere_fit_rmse_mm", "Visible surface sphere-fit RMSE"),
        extraction_paths=("surface_sphere_fit_rmse_mm", "surface_geometry.sphere_fit_rmse_mm"),
    ),
    "surface_sphere_fit_rmse_norm": FeatureDefinition(
        feature_key="surface_sphere_fit_rmse_norm",
        display_name="Normalized sphere-fit RMSE",
        family="sphere_consistency",
        family_label="Sphere consistency",
        source_stage="measurement",
        unit="ratio",
        formula="surface_sphere_fit_rmse_mm / reference_diameter_mm",
        algorithm_summary="Scale-normalized visible-surface sphere-fit RMSE using the selected/reference diameter fallback chain.",
        inputs=("surface_sphere_fit_rmse_mm", "reference diameter"),
        interpretation="Lower values indicate a tighter sphere fit relative to object size.",
        caveats=("Reference diameter uses diameter_selected, fitted sphere diameter, equivalent diameter, or max extents in that order.",),
        stable_schema=True,
        diagnostic_only=False,
        higher_is_worse=True,
        display_precision=4,
        studio_stage="measurement",
        source_metric_path="objects[].sphere_consistency.surface_sphere_fit_rmse_norm",
        extraction_paths=("sphere_consistency.surface_sphere_fit_rmse_norm",),
    ),
    "surface_sphere_fit_residual_p95_norm": FeatureDefinition(
        feature_key="surface_sphere_fit_residual_p95_norm",
        display_name="Sphere residual P95 / diameter",
        family="sphere_consistency",
        family_label="Sphere consistency",
        source_stage="measurement",
        unit="ratio",
        formula="p95(abs(sphere_residual_mm)) / reference_diameter_mm",
        algorithm_summary="Robust high-error sphere residual normalized by reference diameter.",
        inputs=("sphere fit residuals", "reference diameter"),
        interpretation="Lower values mean tail sphere-fit errors remain modest relative to size.",
        stable_schema=True,
        diagnostic_only=False,
        higher_is_worse=True,
        display_precision=4,
        studio_stage="measurement",
        source_metric_path="objects[].sphere_consistency.surface_sphere_fit_residual_p95_norm",
        extraction_paths=("sphere_consistency.surface_sphere_fit_residual_p95_norm",),
    ),
    "surface_sphere_fit_residual_mad_norm": FeatureDefinition(
        feature_key="surface_sphere_fit_residual_mad_norm",
        display_name="Sphere residual MAD / diameter",
        family="sphere_consistency",
        family_label="Sphere consistency",
        source_stage="measurement",
        unit="ratio",
        formula="1.4826 * median(abs(residual - median(residual))) / reference_diameter_mm",
        algorithm_summary="Robust residual dispersion normalized by reference diameter.",
        inputs=("sphere fit residuals", "reference diameter"),
        interpretation="Lower values indicate tighter, more consistent sphere residuals with less sensitivity to edge outliers than RMSE.",
        stable_schema=True,
        diagnostic_only=False,
        higher_is_worse=True,
        display_precision=4,
        studio_stage="measurement",
        source_metric_path="objects[].sphere_consistency.surface_sphere_fit_residual_mad_norm",
        extraction_paths=("sphere_consistency.surface_sphere_fit_residual_mad_norm",),
    ),
    "surface_sphere_radius_error_norm": FeatureDefinition(
        feature_key="surface_sphere_radius_error_norm",
        display_name="Sphere radius plausibility error",
        family="sphere_consistency",
        family_label="Sphere consistency",
        source_stage="measurement",
        unit="ratio",
        formula="abs(2 * fitted_radius_mm - reference_diameter_mm) / reference_diameter_mm",
        algorithm_summary="Normalized mismatch between fitted sphere diameter and selected/reference diameter.",
        inputs=("fitted sphere radius", "reference diameter"),
        interpretation="Lower values mean the fitted sphere radius is physically plausible for the object size.",
        stable_schema=True,
        diagnostic_only=False,
        higher_is_worse=True,
        display_precision=4,
        studio_stage="measurement",
        source_metric_path="objects[].sphere_consistency.surface_sphere_radius_error_norm",
        extraction_paths=("sphere_consistency.surface_sphere_radius_error_norm",),
    ),
    "surface_sphere_center_depth_ratio": FeatureDefinition(
        feature_key="surface_sphere_center_depth_ratio",
        display_name="Sphere center depth ratio",
        family="sphere_consistency",
        family_label="Sphere consistency",
        source_stage="measurement",
        unit="ratio",
        formula="abs(fitted_center_z_mm - expected_center_z_mm) / reference_diameter_mm",
        algorithm_summary="Diagnostic depth mismatch between fitted sphere center Z and expected center Z for a belt-supported sphere.",
        inputs=("fitted sphere center", "expected sphere center", "reference diameter", "visible cap fraction"),
        interpretation="Lower values mean the fitted center depth is more consistent with a plausible ball geometry.",
        caveats=(
            "Emitted as null when visible cap coverage is too low or expected center depth is unreliable.",
            "Diagnostic-only until the expected center model is validated across poses and segmentation styles.",
        ),
        stable_schema=False,
        diagnostic_only=True,
        higher_is_worse=True,
        display_precision=4,
        studio_stage="measurement",
        source_metric_path="objects[].sphere_consistency.surface_sphere_center_depth_ratio",
        extraction_paths=("sphere_consistency.surface_sphere_center_depth_ratio",),
    ),
    "surface_visible_cap_fraction": FeatureDefinition(
        feature_key="surface_visible_cap_fraction",
        display_name="Visible spherical cap fraction",
        family="sphere_consistency",
        family_label="Sphere consistency",
        source_stage="measurement",
        unit="ratio",
        formula="clamp(height_p95_mm / (2 * fitted_radius_mm), 0, 1)",
        algorithm_summary="Visible cap height relative to fitted sphere diameter; distinguishes shallow caps from fuller ball-like objects.",
        inputs=("height_p95_mm", "fitted sphere radius"),
        interpretation="Higher values indicate a fuller visible spherical cap.",
        caveats=("Raw unclamped cap fraction is persisted separately for diagnostics.",),
        stable_schema=True,
        diagnostic_only=False,
        higher_is_worse=False,
        display_precision=4,
        studio_stage="measurement",
        source_metric_path="objects[].sphere_consistency.surface_visible_cap_fraction",
        extraction_paths=("sphere_consistency.surface_visible_cap_fraction",),
    ),
    "surface_volume_fill_ratio": FeatureDefinition(
        feature_key="surface_volume_fill_ratio",
        display_name="Volume fill ratio",
        family="sphere_consistency",
        family_label="Sphere consistency",
        source_stage="measurement",
        unit="ratio",
        formula="feature_volume_proxy_mm3 / expected_volume_mm3",
        algorithm_summary="Measured volume proxy divided by expected full-sphere or spherical-cap volume.",
        inputs=("feature_volume_proxy_mm3", "reference diameter", "fitted radius", "cap height"),
        interpretation="Lower values suggest partial, truncated, or flat objects that only fit a sphere locally.",
        caveats=("Expected-volume model metadata is persisted as sphere, spherical_cap, or unavailable.",),
        stable_schema=True,
        diagnostic_only=False,
        higher_is_worse=False,
        display_precision=4,
        studio_stage="measurement",
        source_metric_path="objects[].sphere_consistency.surface_volume_fill_ratio",
        extraction_paths=("sphere_consistency.surface_volume_fill_ratio",),
    ),
    "surface_sphere_vs_ellipsoid_gain": FeatureDefinition(
        feature_key="surface_sphere_vs_ellipsoid_gain",
        display_name="Sphere vs ellipsoid gain",
        family="sphere_consistency",
        family_label="Sphere consistency",
        source_stage="measurement",
        unit="ratio",
        formula="max(0, (sphere_rmse_mm - ellipsoid_rmse_mm) / sphere_rmse_mm)",
        algorithm_summary="Relative RMSE improvement when an ellipsoid fit is available.",
        inputs=("sphere fit RMSE", "ellipsoid fit RMSE"),
        interpretation="Higher values mean the ellipsoid fit improves substantially over the sphere, suggesting deformation.",
        caveats=("Null when ellipsoid fit is unavailable.",),
        stable_schema=False,
        diagnostic_only=True,
        higher_is_worse=True,
        display_precision=4,
        studio_stage="measurement",
        source_metric_path="objects[].sphere_consistency.surface_sphere_vs_ellipsoid_gain",
        extraction_paths=("sphere_consistency.surface_sphere_vs_ellipsoid_gain", "surface_geometry.sphere_vs_ellipsoid_gain"),
    ),
    "surface_sphere_fit_confidence": FeatureDefinition(
        feature_key="surface_sphere_fit_confidence",
        display_name="Sphere fit confidence",
        family="sphere_consistency",
        family_label="Sphere consistency",
        source_stage="measurement",
        unit="score",
        formula="Weighted heuristic over point count, cap fraction, normalized residuals, radius plausibility, segmentation quality, and border clipping",
        algorithm_summary="Deterministic diagnostic confidence score for trusting sphere-based measurements.",
        inputs=("sphere fit validity", "point count", "visible cap fraction", "normalized residuals", "radius plausibility", "segmentation coverage"),
        interpretation="Higher values mean sphere-fit diagnostics are more trustworthy.",
        caveats=("Diagnostic-only heuristic; component weights are persisted in metadata.",),
        stable_schema=True,
        diagnostic_only=True,
        higher_is_worse=False,
        display_precision=3,
        studio_stage="measurement",
        source_metric_path="objects[].sphere_consistency.surface_sphere_fit_confidence",
        extraction_paths=("sphere_consistency.surface_sphere_fit_confidence",),
    ),
    "feature_local_curvature_proxy": FeatureDefinition(
        feature_key="feature_local_curvature_proxy",
        display_name="Local curvature proxy",
        family="surface_shape",
        family_label="Surface shape",
        source_stage="measurement",
        unit="score",
        formula="mean local height-gradient / curvature proxy over the inner-eroded object mask, with correction-scale normalization when available",
        algorithm_summary="Estimates local surface variation from height gradients. It is a proxy for curvature/roughness, not a true fitted curvature model.",
        inputs=("normalized height gradients", "inner-eroded object mask", "correction-scale normalization"),
        interpretation="Higher values indicate stronger local surface variation.",
        caveats=(
            "This is a proxy derived from local height gradients, not true differential surface curvature.",
            "Sensitive to noise, mask erosion, and spatial scale.",
        ),
        stable_schema=False,
        diagnostic_only=True,
        experimental=True,
        higher_is_worse=True,
        display_precision=3,
        studio_stage="measurement",
        source_metric_path="objects[].feature_local_curvature_proxy",
        legacy_aliases=("local curvature proxy",),
        extraction_paths=("feature_local_curvature_proxy",),
    ),
    "feature_height_asymmetry": FeatureDefinition(
        feature_key="feature_height_asymmetry",
        display_name="Height asymmetry proxy",
        family="surface_shape",
        family_label="Surface shape",
        source_stage="measurement",
        unit="score",
        formula="Asymmetry proxy over the visible normalized-height distribution",
        algorithm_summary="Diagnostic proxy capturing imbalance in the height distribution across the visible object surface.",
        inputs=("normalized heightmap", "object mask"),
        interpretation="Higher values indicate a more asymmetric visible height profile.",
        caveats=("Diagnostic-only proxy feature. Interpretation depends on object pose, visible cap coverage, and segmentation quality.",),
        stable_schema=False,
        diagnostic_only=True,
        experimental=True,
        higher_is_worse=True,
        display_precision=3,
        studio_stage="measurement",
        source_metric_path="objects[].feature_height_asymmetry",
        extraction_paths=("feature_height_asymmetry",),
    ),
    "surface_deformation_score": FeatureDefinition(
        feature_key="surface_deformation_score",
        display_name="Surface deformation score",
        family="sphere_consistency",
        family_label="Sphere consistency",
        source_stage="measurement",
        unit="score",
        formula="clamp(0.7 * sphere_vs_ellipsoid_gain + 0.3 * max(ellipsoid_aspect_ratio - 1, 0), 0, 1)",
        algorithm_summary="Composite heuristic score summarizing how much the visible surface prefers an ellipsoid over a sphere.",
        inputs=("sphere_vs_ellipsoid_gain", "ellipsoid_aspect_ratio"),
        interpretation="Higher values suggest stronger deformation or ellipsoid-like deviation from a sphere.",
        caveats=("Composite heuristic score derived from visible-surface fits only.",),
        stable_schema=True,
        diagnostic_only=False,
        higher_is_worse=True,
        expected_range=(0.0, 1.0),
        display_precision=3,
        studio_stage="measurement",
        source_metric_path="objects[].surface_geometry.deformation_score",
        legacy_aliases=("deformation_score",),
        extraction_paths=("surface_deformation_score", "surface_geometry.deformation_score"),
    ),
    "damage_flat_region_ratio": FeatureDefinition(
        feature_key="damage_flat_region_ratio",
        display_name="Flat-region area ratio",
        family="damage_metrics",
        family_label="Damage / deformation",
        source_stage="measurement",
        unit="ratio",
        formula="count(inner pixels with gradient magnitude < threshold) / count(inner pixels)",
        algorithm_summary="Measures how much of the inner surface area is locally flat under the damage heuristic.",
        inputs=("inner object mask", "gradient magnitude threshold"),
        interpretation="Higher values mean larger low-gradient / flat surface regions.",
        caveats=("Can rise because of genuine damage, truncation, or over-smoothed segmentation.",),
        stable_schema=True,
        diagnostic_only=False,
        higher_is_worse=True,
        expected_range=(0.0, 1.0),
        display_precision=3,
        studio_stage="measurement",
        source_metric_path="objects[].damage_metrics.flat_region_ratio",
        legacy_aliases=("flat_region_ratio",),
        extraction_paths=("damage_flat_region_ratio", "damage_metrics.flat_region_ratio"),
    ),
    "damage_surface_discontinuity_score": FeatureDefinition(
        feature_key="damage_surface_discontinuity_score",
        display_name="Surface discontinuity score",
        family="damage_metrics",
        family_label="Damage / deformation",
        source_stage="measurement",
        unit="score",
        formula="mean(abs(Laplacian(normalized_height))) over inner object mask",
        algorithm_summary="Aggregates local second-derivative height discontinuities over the inner object mask.",
        inputs=("normalized heightmap", "inner object mask", "Laplacian response"),
        interpretation="Higher values indicate stronger local height discontinuities.",
        caveats=("Sensitive to measurement noise and missing-data edges as well as true surface damage.",),
        stable_schema=True,
        diagnostic_only=False,
        higher_is_worse=True,
        display_precision=3,
        studio_stage="measurement",
        source_metric_path="objects[].damage_metrics.surface_discontinuity_score",
        legacy_aliases=("surface_discontinuity_score",),
        extraction_paths=("damage_surface_discontinuity_score", "damage_metrics.surface_discontinuity_score"),
    ),
    "confidence": FeatureDefinition(
        feature_key="confidence",
        display_name="Classification confidence",
        family="classification_diagnostics",
        family_label="Classification diagnostics",
        source_stage="classification",
        unit="score",
        formula="Classifier confidence / rule confidence emitted by the active pipeline",
        algorithm_summary="Reports the classifier or heuristic confidence associated with the processed class label.",
        inputs=("classifier logits or rule confidence"),
        interpretation="Higher values indicate the pipeline was more confident in the processed class decision.",
        caveats=("Confidence calibration depends on the pipeline and should not be compared blindly across models.",),
        stable_schema=False,
        diagnostic_only=True,
        higher_is_worse=False,
        expected_range=(0.0, 1.0),
        display_precision=3,
        studio_stage="classification",
        source_metric_path="objects[].confidence",
        legacy_aliases=("Classification confidence",),
        extraction_paths=("confidence",),
    ),
    "valid_pixel_ratio": FeatureDefinition(
        feature_key="valid_pixel_ratio",
        display_name="Valid pixel ratio",
        family="data_quality",
        family_label="Data quality / coverage",
        source_stage="measurement_diagnostics",
        unit="ratio",
        formula="valid_pixels / total_pixels",
        algorithm_summary="Fraction of ROI pixels carrying valid height information.",
        inputs=("valid height mask", "ROI pixel count"),
        interpretation="Higher values mean better data coverage.",
        caveats=("Diagnostic-only feature from measurement-quality artifacts when available.",),
        stable_schema=False,
        diagnostic_only=True,
        higher_is_worse=False,
        expected_range=(0.0, 1.0),
        display_precision=3,
        studio_stage="measurement",
        source_metric_path="objects[].valid_pixel_ratio",
        extraction_paths=("valid_pixel_ratio",),
    ),
    "invalid_pixel_ratio": FeatureDefinition(
        feature_key="invalid_pixel_ratio",
        display_name="Invalid pixel ratio",
        family="data_quality",
        family_label="Data quality / coverage",
        source_stage="measurement_diagnostics",
        unit="ratio",
        formula="invalid_pixels / total_pixels",
        algorithm_summary="Fraction of ROI pixels without valid height information.",
        inputs=("invalid height mask", "ROI pixel count"),
        interpretation="Higher values mean weaker valid-height coverage.",
        caveats=("Diagnostic-only feature from measurement-quality artifacts when available.",),
        stable_schema=False,
        diagnostic_only=True,
        higher_is_worse=True,
        expected_range=(0.0, 1.0),
        display_precision=3,
        studio_stage="measurement",
        source_metric_path="objects[].invalid_pixel_ratio",
        extraction_paths=("invalid_pixel_ratio",),
    ),
    "border_touch_ratio": FeatureDefinition(
        feature_key="border_touch_ratio",
        display_name="Border touch ratio",
        family="segmentation_quality",
        family_label="Segmentation quality",
        source_stage="segmentation",
        unit="ratio",
        formula="border_touch_pixels / object_pixels",
        algorithm_summary="Measures how much of the segmented object footprint touches the crop/ROI border.",
        inputs=("object mask", "crop border"),
        interpretation="Higher values suggest truncation or crop leakage.",
        caveats=("Diagnostic-only segmentation/cropping quality signal.",),
        stable_schema=False,
        diagnostic_only=True,
        higher_is_worse=True,
        expected_range=(0.0, 1.0),
        display_precision=3,
        studio_stage="segmentation",
        source_metric_path="objects[].border_touch_ratio",
        extraction_paths=("border_touch_ratio",),
    ),
    "segmentation_foreground_ratio": FeatureDefinition(
        feature_key="segmentation_foreground_ratio",
        display_name="Segmentation foreground ratio",
        family="segmentation_quality",
        family_label="Segmentation quality",
        source_stage="segmentation",
        unit="ratio",
        formula="foreground_pixels / ROI_pixels",
        algorithm_summary="Foreground occupancy of the segmentation crop or ROI.",
        inputs=("foreground mask", "ROI pixel count"),
        interpretation="Helps spot under/over-segmentation and crop mismatch.",
        caveats=("Diagnostic-only segmentation occupancy metric.",),
        stable_schema=False,
        diagnostic_only=True,
        higher_is_worse=None,
        expected_range=(0.0, 1.0),
        display_precision=3,
        studio_stage="segmentation",
        source_metric_path="objects[].segmentation_foreground_ratio",
        extraction_paths=("segmentation_foreground_ratio",),
    ),
    "bbox_crop_ratio": FeatureDefinition(
        feature_key="bbox_crop_ratio",
        display_name="BBox crop ratio",
        family="segmentation_quality",
        family_label="Segmentation quality",
        source_stage="segmentation",
        unit="ratio",
        formula="object_bbox_area / crop_area",
        algorithm_summary="How much of the crop area is occupied by the object bounding box.",
        inputs=("object bbox", "crop area"),
        interpretation="Helps identify overly tight or overly loose crops.",
        caveats=("Diagnostic-only crop-quality metric.",),
        stable_schema=False,
        diagnostic_only=True,
        higher_is_worse=None,
        expected_range=(0.0, 1.0),
        display_precision=3,
        studio_stage="segmentation",
        source_metric_path="objects[].bbox_crop_ratio",
        extraction_paths=("bbox_crop_ratio",),
    ),
    "roi_occupancy_ratio": FeatureDefinition(
        feature_key="roi_occupancy_ratio",
        display_name="ROI occupancy ratio",
        family="segmentation_quality",
        family_label="Segmentation quality",
        source_stage="segmentation",
        unit="ratio",
        formula="object_pixels / ROI_pixels",
        algorithm_summary="Foreground occupancy over the ROI used for measurement diagnostics.",
        inputs=("object mask", "ROI mask"),
        interpretation="Useful for spotting weak occupancy or oversized ROI framing.",
        caveats=("Diagnostic-only ROI coverage metric.",),
        stable_schema=False,
        diagnostic_only=True,
        higher_is_worse=None,
        expected_range=(0.0, 1.0),
        display_precision=3,
        studio_stage="segmentation",
        source_metric_path="objects[].roi_occupancy_ratio",
        extraction_paths=("roi_occupancy_ratio",),
    ),
    "plane_residual_mean": FeatureDefinition(
        feature_key="plane_residual_mean",
        display_name="Plane residual mean",
        family="plane_quality",
        family_label="Plane fit quality",
        source_stage="detect_belt_plane",
        unit="mm",
        formula="mean(plane_fit_residual_mm)",
        algorithm_summary="Average residual from the detected reference-surface/plane model.",
        inputs=("plane-fit residuals"),
        interpretation="Higher values indicate poorer reference-surface fit quality.",
        caveats=("Diagnostic-only calibration/reference-surface metric.",),
        stable_schema=False,
        diagnostic_only=True,
        higher_is_worse=True,
        display_precision=3,
        studio_stage="detect_belt_plane",
        source_metric_path="objects[].plane_residual_mean",
        extraction_paths=("plane_residual_mean",),
    ),
    "plane_residual_std": FeatureDefinition(
        feature_key="plane_residual_std",
        display_name="Plane residual std",
        family="plane_quality",
        family_label="Plane fit quality",
        source_stage="detect_belt_plane",
        unit="mm",
        formula="std(plane_fit_residual_mm)",
        algorithm_summary="Spread of residuals from the detected reference-surface/plane model.",
        inputs=("plane-fit residuals"),
        interpretation="Higher values indicate noisier or less consistent reference-surface fit quality.",
        caveats=("Diagnostic-only calibration/reference-surface metric.",),
        stable_schema=False,
        diagnostic_only=True,
        higher_is_worse=True,
        display_precision=3,
        studio_stage="detect_belt_plane",
        source_metric_path="objects[].plane_residual_std",
        extraction_paths=("plane_residual_std",),
    ),
    "plane_residual_p95": FeatureDefinition(
        feature_key="plane_residual_p95",
        display_name="Plane residual P95",
        family="plane_quality",
        family_label="Plane fit quality",
        source_stage="detect_belt_plane",
        unit="mm",
        formula="percentile(plane_fit_residual_mm, 95)",
        algorithm_summary="Near-tail residual magnitude from the detected reference-surface/plane model.",
        inputs=("plane-fit residuals"),
        interpretation="Higher values indicate stronger reference-surface outliers.",
        caveats=("Diagnostic-only calibration/reference-surface metric.",),
        stable_schema=False,
        diagnostic_only=True,
        higher_is_worse=True,
        display_precision=3,
        studio_stage="detect_belt_plane",
        source_metric_path="objects[].plane_residual_p95",
        extraction_paths=("plane_residual_p95",),
    ),
    "height_min": FeatureDefinition(
        feature_key="height_min",
        display_name="Min height",
        family="data_quality",
        family_label="Data quality / coverage",
        source_stage="measurement_diagnostics",
        unit="mm",
        formula="min(height_above_belt_mm) over diagnostic ROI",
        algorithm_summary="Diagnostic min height from measurement-quality feature vectors.",
        inputs=("normalized heightmap", "diagnostic ROI"),
        interpretation="Useful for sanity-checking negative or clipped background values.",
        caveats=("Diagnostic-only measurement-quality feature.",),
        stable_schema=False,
        diagnostic_only=True,
        higher_is_worse=None,
        display_precision=2,
        studio_stage="measurement",
        source_metric_path="objects[].height_min",
        extraction_paths=("height_min",),
    ),
    "height_max": FeatureDefinition(
        feature_key="height_max",
        display_name="Diagnostic max height",
        family="data_quality",
        family_label="Data quality / coverage",
        source_stage="measurement_diagnostics",
        unit="mm",
        formula="max(height_above_belt_mm) over diagnostic ROI",
        algorithm_summary="Diagnostic max height from measurement-quality feature vectors.",
        inputs=("normalized heightmap", "diagnostic ROI"),
        interpretation="Useful for comparing diagnostic feature vectors to stable exported height metrics.",
        caveats=("Diagnostic-only measurement-quality feature distinct from stable height_max_mm.",),
        stable_schema=False,
        diagnostic_only=True,
        higher_is_worse=None,
        display_precision=2,
        studio_stage="measurement",
        source_metric_path="objects[].height_max",
        extraction_paths=("height_max",),
    ),
    "height_mean": FeatureDefinition(
        feature_key="height_mean",
        display_name="Diagnostic mean height",
        family="data_quality",
        family_label="Data quality / coverage",
        source_stage="measurement_diagnostics",
        unit="mm",
        formula="mean(height_above_belt_mm) over diagnostic ROI",
        algorithm_summary="Diagnostic mean height from measurement-quality feature vectors.",
        inputs=("normalized heightmap", "diagnostic ROI"),
        interpretation="Useful for diagnostic comparisons and QA thresholds.",
        caveats=("Diagnostic-only measurement-quality feature distinct from stable height_mean_mm.",),
        stable_schema=False,
        diagnostic_only=True,
        higher_is_worse=None,
        display_precision=2,
        studio_stage="measurement",
        source_metric_path="objects[].height_mean",
        extraction_paths=("height_mean",),
    ),
    "height_std": FeatureDefinition(
        feature_key="height_std",
        display_name="Height std",
        family="data_quality",
        family_label="Data quality / coverage",
        source_stage="measurement_diagnostics",
        unit="mm",
        formula="std(height_above_belt_mm) over diagnostic ROI",
        algorithm_summary="Diagnostic spread of height values over the ROI.",
        inputs=("normalized heightmap", "diagnostic ROI"),
        interpretation="Higher values indicate broader height variation across the measured ROI.",
        caveats=("Diagnostic-only measurement-quality feature.",),
        stable_schema=False,
        diagnostic_only=True,
        higher_is_worse=None,
        display_precision=2,
        studio_stage="measurement",
        source_metric_path="objects[].height_std",
        extraction_paths=("height_std",),
    ),
    "height_p95": FeatureDefinition(
        feature_key="height_p95",
        display_name="Height P95",
        family="data_quality",
        family_label="Data quality / coverage",
        source_stage="measurement_diagnostics",
        unit="mm",
        formula="percentile(height_above_belt_mm, 95) over diagnostic ROI",
        algorithm_summary="Diagnostic P95 height over the ROI.",
        inputs=("normalized heightmap", "diagnostic ROI"),
        interpretation="Tracks near-peak height in diagnostic feature vectors.",
        caveats=("Diagnostic-only measurement-quality feature.",),
        stable_schema=False,
        diagnostic_only=True,
        higher_is_worse=None,
        display_precision=2,
        studio_stage="measurement",
        source_metric_path="objects[].height_p95",
        extraction_paths=("height_p95",),
    ),
    "height_p99": FeatureDefinition(
        feature_key="height_p99",
        display_name="Height P99",
        family="data_quality",
        family_label="Data quality / coverage",
        source_stage="measurement_diagnostics",
        unit="mm",
        formula="percentile(height_above_belt_mm, 99) over diagnostic ROI",
        algorithm_summary="Diagnostic P99 height over the ROI.",
        inputs=("normalized heightmap", "diagnostic ROI"),
        interpretation="Useful for spotting extreme height outliers.",
        caveats=("Diagnostic-only measurement-quality feature.",),
        stable_schema=False,
        diagnostic_only=True,
        higher_is_worse=None,
        display_precision=2,
        studio_stage="measurement",
        source_metric_path="objects[].height_p99",
        extraction_paths=("height_p99",),
    ),
    "equivalent_diameter_mm": FeatureDefinition(
        feature_key="equivalent_diameter_mm",
        display_name="Equivalent diameter",
        family="surface_shape",
        family_label="Surface shape",
        source_stage="measurement_diagnostics",
        unit="mm",
        formula="sqrt(4 * footprint_area_mm2 / pi)",
        algorithm_summary="Equivalent circular diameter derived from the segmented footprint area.",
        inputs=("footprint area"),
        interpretation="Useful as a diagnostic size proxy for the visible footprint.",
        caveats=("Diagnostic-only feature here; depends on visible footprint, not full object volume.",),
        stable_schema=False,
        diagnostic_only=True,
        higher_is_worse=None,
        display_precision=2,
        studio_stage="measurement",
        source_metric_path="objects[].equivalent_diameter_mm",
        extraction_paths=("equivalent_diameter_mm",),
    ),
    "compactness": FeatureDefinition(
        feature_key="compactness",
        display_name="Compactness",
        family="surface_shape",
        family_label="Surface shape",
        source_stage="measurement_diagnostics",
        unit="ratio",
        formula="4 * pi * area / perimeter^2",
        algorithm_summary="Diagnostic compactness computed from footprint area and perimeter.",
        inputs=("footprint area", "footprint perimeter"),
        interpretation="Higher values indicate a more compact footprint.",
        caveats=("Diagnostic-only 2D footprint feature.",),
        stable_schema=False,
        diagnostic_only=True,
        higher_is_worse=False,
        display_precision=3,
        studio_stage="measurement",
        source_metric_path="objects[].compactness",
        extraction_paths=("compactness",),
    ),
    "solidity": FeatureDefinition(
        feature_key="solidity",
        display_name="Solidity",
        family="surface_shape",
        family_label="Surface shape",
        source_stage="measurement_diagnostics",
        unit="ratio",
        formula="footprint_area / convex_hull_area",
        algorithm_summary="Diagnostic solidity derived from the 2D footprint convex hull.",
        inputs=("footprint area", "convex hull area"),
        interpretation="Lower values indicate more concave or fragmented footprint shapes.",
        caveats=("Diagnostic-only 2D footprint feature.",),
        stable_schema=False,
        diagnostic_only=True,
        higher_is_worse=False,
        display_precision=3,
        studio_stage="measurement",
        source_metric_path="objects[].solidity",
        extraction_paths=("solidity",),
    ),
    "convex_volume_proxy": FeatureDefinition(
        feature_key="convex_volume_proxy",
        display_name="Convex volume proxy",
        family="volume_proxy",
        family_label="Volume / mass proxy",
        source_stage="measurement_diagnostics",
        unit="mm3",
        formula="footprint_area_mm2 * height_p95_mm",
        algorithm_summary="Diagnostic convex-envelope-style volume proxy using footprint area and high-percentile height.",
        inputs=("footprint area", "height_p95"),
        interpretation="Higher values indicate larger visible object bulk.",
        caveats=("Diagnostic-only proxy, not true volume or mass.",),
        stable_schema=False,
        diagnostic_only=True,
        higher_is_worse=None,
        display_precision=1,
        studio_stage="measurement",
        source_metric_path="objects[].convex_volume_proxy",
        extraction_paths=("convex_volume_proxy",),
    ),
}


def guess_feature_source_stage(feature_key: str) -> str:
    if feature_key.startswith("plane_residual_"):
        return "detect_belt_plane"
    if feature_key in {"confidence"}:
        return "classification"
    if feature_key in {"valid_pixel_ratio", "invalid_pixel_ratio", "bbox_crop_ratio", "roi_occupancy_ratio", "border_touch_ratio", "segmentation_foreground_ratio"}:
        return "segmentation"
    if feature_key.startswith("runtime_"):
        return "classification"
    return "measurement"


def guess_feature_family(feature_key: str) -> tuple[str, str]:
    if feature_key in {"confidence"}:
        return "classification_diagnostics", "Classification diagnostics"
    if feature_key.startswith("plane_residual_"):
        return "plane_quality", "Plane fit quality"
    if feature_key in {"valid_pixel_ratio", "invalid_pixel_ratio", "height_min", "height_max", "height_mean", "height_std", "height_p95", "height_p99"}:
        return "data_quality", "Data quality / coverage"
    if feature_key in {"border_touch_ratio", "segmentation_foreground_ratio", "bbox_crop_ratio", "roi_occupancy_ratio"}:
        return "segmentation_quality", "Segmentation quality"
    if feature_key.endswith("_mm3") or "volume" in feature_key:
        return "volume_proxy", "Volume / mass proxy"
    if "sphere" in feature_key or "deformation" in feature_key or "curvature" in feature_key:
        return "sphere_consistency", "Sphere consistency"
    if "height" in feature_key:
        return "height_metrics", "Height metrics"
    if "damage" in feature_key or "roughness" in feature_key:
        return "damage_metrics", "Damage / deformation"
    if "eccentricity" in feature_key or "radial" in feature_key or "roundness" in feature_key or "compactness" in feature_key or "solidity" in feature_key:
        return "footprint_geometry", "Footprint geometry"
    return "data_quality", "Diagnostic / engineering features"


def guess_feature_unit(feature_key: str) -> str | None:
    if feature_key.endswith("_mm3") or "volume" in feature_key:
        return "mm3"
    if feature_key.endswith("_mm2"):
        return "mm2"
    if feature_key.endswith("_mm") or "residual" in feature_key:
        return "mm"
    if feature_key.endswith("_ratio") or "eccentricity" in feature_key or "roundness" in feature_key or "compactness" in feature_key or "solidity" in feature_key or "confidence" == feature_key:
        return "ratio"
    if "score" in feature_key or "confidence" in feature_key or "flatness" in feature_key:
        return "score"
    return None


def fallback_feature_definition(feature_key: str) -> FeatureDefinition:
    family, family_label = guess_feature_family(feature_key)
    source_stage = guess_feature_source_stage(feature_key)
    unit = guess_feature_unit(feature_key)
    return FeatureDefinition(
        feature_key=feature_key,
        display_name=feature_key.replace("_", " ").strip().title(),
        family=family,
        family_label=family_label,
        source_stage=source_stage,
        unit=unit,
        formula="TODO",
        algorithm_summary="Feature discovered from result payload without a curated catalog entry yet.",
        inputs=("object result payload",),
        interpretation="Use with caution until the canonical feature catalog entry is completed.",
        caveats=("Catalog metadata is still incomplete for this feature.",),
        stable_schema=False,
        diagnostic_only=True,
        experimental=True,
        higher_is_worse=None,
        preferred_chart_scale="linear",
        studio_stage=source_stage,
        source_metric_path=f"objects[].{feature_key}",
        extraction_paths=(feature_key,),
    )


def feature_definition_for_key(feature_key: str) -> FeatureDefinition:
    return FEATURE_REGISTRY.get(feature_key) or fallback_feature_definition(feature_key)


def all_registered_feature_definitions() -> list[dict[str, Any]]:
    return [feature_definition_for_key(key).payload() for key in sorted(FEATURE_REGISTRY)]


def discover_numeric_object_feature_keys(raw_object: dict[str, Any]) -> set[str]:
    discovered: set[str] = set()
    for key, definition in FEATURE_REGISTRY.items():
        for path in definition.extraction_paths:
            if path and numeric_path_exists(raw_object, path):
                discovered.add(key)
                break
    return discovered


def numeric_path_exists(raw_object: dict[str, Any], path: str) -> bool:
    current: Any = raw_object
    for part in path.split("."):
        if not isinstance(current, dict):
            return False
        current = current.get(part)
    return isinstance(current, (int, float)) and not isinstance(current, bool)


def stable_schema_feature_keys() -> set[str]:
    return set(FEATURE_COLUMNS)


def feature_job_reprocess_keys() -> frozenset[str]:
    """Features emitted by a full 25D pipeline reprocess (sphere-consistency family)."""
    return frozenset(
        key
        for key, definition in FEATURE_REGISTRY.items()
        if definition.family == "sphere_consistency" and definition.source_stage == "measurement"
    )


def feature_job_backfill_keys() -> frozenset[str]:
    """Features with a lightweight backfill workflow (sidecar recompute without full reprocess)."""
    return frozenset({"surface_sphere_fit_rmse_mm"})
