import WizardStepLayout from "./WizardStepLayout";

type GroupingSummary = {
  physical_object_count?: number;
  take_count?: number;
  rows_with_object_id?: number;
  rows_missing_object_id?: number;
  conflict_count?: number;
  distribution_by_superclass?: Record<string, number>;
  distribution_by_normalized_class?: Record<string, number>;
  warnings?: string[];
};

type ConflictRow = {
  physical_object_id?: string;
  conflicts?: Record<string, string[]>;
};

export default function PhysicalObjectGroupingStep({ summary, conflicts }: { summary?: unknown; conflicts?: unknown }) {
  const grouping = (summary && typeof summary === "object") ? (summary as GroupingSummary) : null;
  const rows = Array.isArray(conflicts) ? (conflicts as ConflictRow[]) : [];
  return (
    <WizardStepLayout title="Physical Object Grouping" description="Group takes by source row into deterministic physical_object_id.">
      {!grouping ? <small>Splits are generated by physical_object_id to avoid leakage.</small> : (
        <>
          <div className="entity-summary-cards ml-set-summary-cards">
            <article><small>physical objects</small><strong>{grouping.physical_object_count ?? 0}</strong></article>
            <article><small>takes</small><strong>{grouping.take_count ?? 0}</strong></article>
            <article><small>rows with object_id</small><strong>{grouping.rows_with_object_id ?? 0}</strong></article>
            <article><small>rows missing object_id</small><strong>{grouping.rows_missing_object_id ?? 0}</strong></article>
            <article><small>conflicts</small><strong>{grouping.conflict_count ?? 0}</strong></article>
            <article><small>leakage-safe</small><strong>{(grouping.rows_missing_object_id ?? 0) === 0 ? "yes" : "weaker"}</strong></article>
          </div>
          <details className="entity-diagnostics" open>
            <summary>Object-level distributions</summary>
            <pre className="datasets-inline-state">{JSON.stringify({
              superclass: grouping.distribution_by_superclass || {},
              normalized_class: grouping.distribution_by_normalized_class || {},
              warnings: grouping.warnings || [],
              leakage_safe_grouping_status: (grouping.rows_missing_object_id ?? 0) === 0 ? "all rows carry object_id/physical_object_id" : "some rows rely on inferred grouping",
            }, null, 2)}</pre>
          </details>
          <details className="entity-diagnostics" open={rows.length > 0}>
            <summary>Conflicts by object_id ({rows.length})</summary>
            <pre className="datasets-inline-state">{JSON.stringify(rows, null, 2)}</pre>
          </details>
          <div style={{ marginTop: 8 }}><small>Completed automatically from rich TSV fields.</small></div>
        </>
      )}
    </WizardStepLayout>
  );
}
