import WizardStepLayout from "./WizardStepLayout";

export default function PhysicalObjectGroupingStep() {
  return <WizardStepLayout title="Physical Object Grouping" description="Group takes by source row into deterministic physical_object_id."><small>Splits are generated by physical_object_id to avoid leakage.</small></WizardStepLayout>;
}
