import test from "node:test";
import assert from "node:assert/strict";
import { readFile } from "node:fs/promises";

test("Processing Lab exposes an expanded graph workspace overlay", async () => {
  const source = await readFile(new URL("../src/pages/ProcessingLabPage.tsx", import.meta.url), "utf8");
  const workspaceSource = await readFile(new URL("../src/components/ProcessingUnitGraphWorkspace.tsx", import.meta.url), "utf8");
  const viewerSource = await readFile(new URL("../src/components/ProcessingUnitGraphViewer.tsx", import.meta.url), "utf8");
  assert.ok(source.includes("Expand graph workspace"));
  assert.ok(source.includes("ProcessingUnitGraphWorkspace"));
  assert.ok(source.includes("graphWorkspaceExpanded"));
  assert.ok(source.includes("planPartialRerunFromSelectedUnit"));
  assert.ok(source.includes("executePartialRerunFromPlan"));
  assert.ok(source.includes("partialRerunPlanStale"));
  assert.ok(source.includes("partialRerunExecution"));
  assert.ok(source.includes("Workflow checklist"));
  assert.ok(source.includes("traceSummary={graphTraceSummary}"));
  assert.ok(workspaceSource.includes("Graph / Compare Workspace"));
  assert.ok(workspaceSource.includes("Edit mode"));
  assert.ok(workspaceSource.includes("Plan rerun from this unit"));
  assert.ok(workspaceSource.includes("Planning only"));
  assert.ok(workspaceSource.includes("Copy plan JSON"));
  assert.ok(workspaceSource.includes("Run partial from boundary"));
  assert.ok(workspaceSource.includes("Parent run will not be modified"));
  assert.ok(workspaceSource.includes("Partial run summary"));
  assert.ok(workspaceSource.includes("Quality / confidence"));
  assert.ok(workspaceSource.includes("Stale plan"));
  assert.ok(workspaceSource.includes("Reset unit to recipe"));
  assert.ok(workspaceSource.includes("Reset unit to last run"));
  assert.ok(workspaceSource.includes("Reset unit to defaults"));
  assert.ok(workspaceSource.includes("Partial rerun plan"));
  assert.ok(workspaceSource.includes("Artifact diff gallery"));
  assert.ok(workspaceSource.includes("Open tune panel"));
  assert.ok(workspaceSource.includes("Runtime trace coverage unavailable"));
  assert.ok(workspaceSource.includes("No processing-unit contract loaded"));
  assert.ok(workspaceSource.includes("No active comparison loaded"));
  assert.ok(workspaceSource.includes("traceBadgeClass"));
  assert.ok(viewerSource.includes("formatTraceCoverageLine"));
  assert.ok(viewerSource.includes("traceBadgeLabel"));
  assert.ok(viewerSource.includes("Legend"));
  assert.ok(viewerSource.includes("stale"));
});
