import { useEffect, useMemo, useState } from "react";
import { api, type ValidationCoverageArea, type ValidationSuiteDetail } from "../api/client";
import { validationStatus, type ValidationStatus } from "../components/validation/validationStatus";

type Matrix = Awaited<ReturnType<typeof api.validationMatrix>>;

export default function ValidationPage() {
  const [suites,setSuites]=useState<Array<{id:string;name:string;pipeline_id:string;status:string}>>([]); const [suiteId,setSuiteId]=useState("");
  const [suite,setSuite]=useState<ValidationSuiteDetail|null>(null); const [coverage,setCoverage]=useState<ValidationCoverageArea[]>([]); const [history,setHistory]=useState<Array<Record<string,unknown>>>([]); const [executionId,setExecutionId]=useState(""); const [matrix,setMatrix]=useState<Matrix|null>(null); const [message,setMessage]=useState(""); const [newName,setNewName]=useState("");
  const refresh=async () => { const rows=await api.validationSuites(); setSuites(rows); const id=suiteId||rows[0]?.id||""; setSuiteId(id); if(id){ const [detail,report,history]=await Promise.all([api.validationSuite(id),api.validationCoverage(id),api.validationExecutions()]); setSuite(detail); setCoverage(report.areas); const latest=history.filter(x=>x.suite_id===id).at(-1); if(latest?.id){setExecutionId(String(latest.id)); setMatrix(await api.validationMatrix(String(latest.id)));} } };
  useEffect(()=>{void refresh().catch(error=>setMessage(error instanceof Error?error.message:"Validation load failed"));},[]);
  const selectSuite=async(id:string)=>{setSuiteId(id); setExecutionId(""); setMatrix(null); const [detail,report,executions]=await Promise.all([api.validationSuite(id),api.validationCoverage(id),api.validationSuiteExecutions(id)]); setSuite(detail); setCoverage(report.areas); setHistory(executions);};
  const run=async()=>{if(!suiteId)return; setMessage("Running suite…"); const execution=await api.runValidationSuite(suiteId); setExecutionId(String(execution.id)); setMatrix(await api.validationMatrix(String(execution.id))); setMessage(String(execution.status));};
  const create=async()=>{if(!newName.trim())return; const created=await api.createValidationSuite({name:newName,pipeline_id:"mining_steel_ball_classification_25d"}); setNewName(""); await refresh(); await selectSuite(created.id);};
  const lifecycle=async(action:"duplicate"|"archive"|"restore")=>{if(!suiteId)return; const updated=action==="duplicate"?await api.duplicateValidationSuite(suiteId):action==="archive"?await api.archiveValidationSuite(suiteId):await api.restoreValidationSuite(suiteId); setMessage(`${action}: ${updated.name}`); await refresh();};
  const selectedCells=useMemo(()=>matrix?.rows.flatMap(row=>row.cells.filter(cell=>cell.first_divergence).map(cell=>`${row.take_id}: ${cell.artifact_id??cell.column_id}`))??[],[matrix]); const loadExecution=async(id:string)=>{setExecutionId(id);setMatrix(await api.validationMatrix(id));}; const badge=(status:string)=>validationStatus[status as ValidationStatus]??{label:status,severity:"muted",icon:"?",tooltip:status};
  return <main className="page-shell"><section className="page-header"><div><p className="eyebrow">Regression governance</p><h1>Validation</h1><p>Approved references, suite coverage, historical executions, and first divergence.</p></div></section>
    <section className="control-panel-section"><div className="control-panel-button-row"><label>Suite <select value={suiteId} onChange={event=>void selectSuite(event.target.value)}>{suites.map(item=><option key={item.id} value={item.id}>{item.name} · {item.status}</option>)}</select></label><input value={newName} placeholder="New suite name" onChange={event=>setNewName(event.target.value)}/><button type="button" onClick={()=>void create()}>Create suite</button><button type="button" disabled={!suite||suite.status==="archived"} onClick={()=>void run()}>Run suite</button><button type="button" disabled={!suite} onClick={()=>void lifecycle("duplicate")}>Duplicate</button>{suite?.status==="archived"?<button type="button" onClick={()=>void lifecycle("restore")}>Restore suite</button>:<button type="button" disabled={!suite} onClick={()=>void lifecycle("archive")}>Archive suite</button>}</div><small>{message}</small></section>
    <section className="control-panel-section"><h2>Cases</h2>{suite?.status==="archived"?<p>Archived suites are read-only. Restore to edit cases or execute.</p>:null}<div className="table-wrap"><table><thead><tr><th>Take</th><th>Enabled</th><th>Resolution</th><th>References</th><th>Tags</th></tr></thead><tbody>{suite?.cases.map(item=><tr key={item.id}><td>{item.take_id}</td><td>{item.enabled?"Enabled":"Disabled"}</td><td>{item.baseline_resolution?.mode??"active"}</td><td>{item.baseline_ids.join(", ")}</td><td>{item.tags.join(", ")||"—"}</td></tr>)}</tbody></table></div></section>
    <section className="control-panel-section"><h2>Coverage</h2><div className="table-wrap"><table><thead><tr><th>Area</th><th>Comparable</th><th>Missing</th><th>Stale</th><th>Unsupported</th><th>Visual-only</th></tr></thead><tbody>{coverage.map(area=><tr key={area.area}><td>{area.area}</td><td>{area.approved}</td><td>{area.missing}</td><td>{area.stale}</td><td>{area.unsupported}</td><td>{area.visual_only}</td></tr>)}</tbody></table></div></section>
    <section className="control-panel-section"><h2>Execution history</h2><div className="table-wrap"><table><thead><tr><th>Execution</th><th>Started</th><th>Status</th><th>Action</th></tr></thead><tbody>{history.map(item=><tr key={String(item.id)}><td>{String(item.id)}</td><td>{String(item.created_at??"—")}</td><td>{String(item.status)}</td><td><button type="button" onClick={()=>void loadExecution(String(item.id))}>Open</button></td></tr>)}</tbody></table></div></section>
    <section className="control-panel-section"><h2>Execution analysis {executionId?`· ${executionId}`:""}</h2>{selectedCells.length? <p>First divergence: {selectedCells.join("; ")}</p>:null}{!matrix?<p>Run or select a suite execution to load the backend-provided contract matrix.</p>:<div className="table-wrap"><table><thead><tr><th>Take</th>{matrix.columns.map(column=><th key={column.id}>{column.label}</th>)}<th>Overall</th></tr></thead><tbody>{matrix.rows.map(row=><tr key={row.case_id}><td>{row.take_id}</td>{row.cells.map(cell=>{const presentation=badge(cell.status); return <td key={cell.column_id}><span title={presentation.tooltip} className={`status-badge ${cell.status}`}>{cell.first_divergence?"◆ ":presentation.icon+" "}{presentation.label}</span></td>})}<td><strong>{badge(row.overall_status).label}</strong></td></tr>)}</tbody></table></div>}</section>
  </main>;
}
